---
title: Simple benchmarks for development
output: html_document
---


```sh
git checkout "0.10.0"
R CMD INSTALL .
```

```{r}
library(marginaleffects)

results <- list()
```

# `slopes()`

## Many factor levels: LM and GLM

```{r}
N <- 1e3
dat <- data.frame(matrix(rnorm(N * 10), ncol = 10))
dat$c1 <- factor(sample(letters, N, replace = TRUE))
dat$c2 <- factor(sample(letters, N, replace = TRUE))
dat$bin <- sample(0:1, N, replace = TRUE)
mod_lm <- lm(X1 ~ ., dat)
mod_glm <- glm(bin ~ ., dat, family = binomial)

results[["many_factor_levels_glm"]] <- bench::mark(
    slopes(mod_lm),
    slopes(mod_glm),
    check = FALSE,
    iterations = 5
)[, 1:5]
results[["many_factor_levels_glm"]]
```

## Many variables and arguments

```{r}
N <- 1e4
dat <- data.frame(matrix(rnorm(N * 26), ncol = 26))
mod <- lm(X1 ~ ., dat)

results[["many_variables_vcov"]] <- bench::mark(
    # marginal effects at the mean; no standard error
    comparisons(mod, vcov = FALSE, newdata = datagrid()),
    # marginal effects at the mean
    comparisons(mod, newdata = datagrid()),
    # 1 variable; no standard error
    comparisons(mod, vcov = FALSE, variables = "X3"),
    # 1 variable
    comparisons(mod, variables = "X3"),
    # 26 variables; no standard error
    comparisons(mod, vcov = FALSE),
    # 26 variables
    # comparisons(mod),
    iterations = 1, check = FALSE
)[, 1:5]
results[["many_variables_vcov"]]
```

## Many factor variables

```{r}
N <- 1e4
dat <- data.frame(lapply(1:10, \(i) as.factor(sample(1:4, N, replace = TRUE))))
dat <- setNames(dat, paste0("X", seq_along(dat)))
dat$y <- rnorm(nrow(dat))
mod <- lm(y ~ ., dat)

results[["many_factor_variables"]] <- bench::mark(
    slopes(mod),
    check = FALSE,
    iterations = 5
)[, 1:5]
results[["many_factor_variables"]]
```

## Tiny

```{r}
mod <- lm(mpg ~ hp + factor(gear) + factor(cyl), mtcars)
results[["tiny"]] <- bench::mark(
    slopes(mod),
    check = FALSE
)[, 1:5]
results[["tiny"]]
```

## Many observations

```{r}
dat <- get_dataset("penguins", "palmerpenguins")
dat$large_penguin <- ifelse(dat$body_mass_g > median(dat$body_mass_g, na.rm = TRUE), 1, 0)
tmp <- list()
for (i in 1:300) tmp[[i]] <- dat
dat2 <- data.table::rbindlist(tmp)
mod <- glm(large_penguin ~ bill_length_mm + flipper_length_mm + species,
           data = dat2, family = binomial)

results[["many_observations"]] <- bench::mark(
    slopes(mod),
    check = FALSE,
    iterations = 5
)[, 1:5]
results[["many_observations"]]
```

## GLM prediction type

```{r}
d <- data.frame(y = sample(0:1, 1e5, replace = TRUE), x1 = rnorm(1e5), x2 = rnorm(1e5))
mod <- glm(y ~ x1 * x2, family = binomial, data = d)
results[["glm_type"]] <- bench::mark(
    avg_slopes(mod, type = "link"),
    avg_slopes(mod, type = "response"),
    check = FALSE,
    iterations = 5
)[, 1:5]
results[["glm_type"]]
```

## Categorical predictors

```{r}
N <- 1e5
dat <- data.frame(
    y = rnorm(N),
    x1 = sample(0:1, N, replace = TRUE),
    x2 = sample(letters[1:3], N, replace = TRUE),
    x3 = sample(letters[1:10], N, replace = TRUE),
    x4 = sample(letters[1:2], N, replace = TRUE))
mod <- lm(y ~ x1 + x2 + x3 + x4, data = dat)
results[["categorical_predictors"]] <- bench::mark(
    avg_comparisons(mod),
    avg_predictions(mod),
    check = FALSE)
results[["categorical_predictors"]]
```

# `predictions()`

## Many factor variables

```{r}
N <- 1e6
dat <- data.frame(lapply(1:20, \(i) as.factor(sample(1:4, N, replace = TRUE))))
dat <- setNames(dat, paste0("X", seq_along(dat)))
dat$y <- rnorm(nrow(dat))
mod <- lm(y ~ ., dat)

results[["predictions_many_factors"]] <- bench::mark(
    predictions(mod),
    check = FALSE,
    iterations = 5
)[, 1:5]
results[["predictions_many_factors"]]
```


# Save results

```{r}
fn <- paste0("benchmarks_", packageVersion("marginaleffects"), ".rds")
saveRDS(results, fn)
```


# Compare results

```{r, eval = FALSE}
library(patchwork)
library(ggplot2)
old <- readRDS("sandbox/benchmarks_0.9.0.rds")
new <- readRDS("sandbox/benchmarks_0.11.0.rds")
new[["tiny"]] <- old[["tiny"]] <- new[["many_variables_vcov"]] <- old[["many_variables_vcov"]] <- NULL

tim <- list()
mem <- list()
for (i in names(old)) {
    tim[[i]] <- old[[i]]$median / new[[i]]$median
    mem[[i]] <- old[[i]]$mem_alloc / new[[i]]$mem_alloc
}
mem <- unlist(mem)
tim <- unlist(tim)

hist(mem)

old[[1]]$median


res <- data.frame(
    old_time = unlist(sapply(old, \(x) x$median)),
    new_time = unlist(sapply(new, \(x) x$median)),
    old_memory = unlist(sapply(old, \(x) x$mem_alloc)),
    new_memory = unlist(sapply(new, \(x) x$mem_alloc))
)

p1 <- ggplot(res, aes(new_time, old_time)) + geom_point()

lapply(old, class)


do.call("rbind", new)

```