<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.43">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Marginal Effects Zoo – Interactions, polynomials, and splines</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../vignettes/ipw.html" rel="next">
<link href="../vignettes/heterogeneity.html" rel="prev">
<link href="../images/favicon.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../images/marginaleffects_icon.png" alt="marginaleffects logo" class="navbar-logo"></a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Marginal Effects Zoo</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item">
    <a class="nav-link active" href="../vignettes/get_started.html" aria-current="page"> 
<span class="menu-text">Get started</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../files/marginaleffects_arel-bundock_greifer_heiss_jss5115.pdf"> 
<span class="menu-text">Article</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../vignettes/help.html"> 
<span class="menu-text">Help</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vincentarelbundock/marginaleffects"> <i class="bi bi-github" role="img" aria-label="marginaleffects GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/vincentab"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
</div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/brms.html">Case studies</a></li><li class="breadcrumb-item"><a href="../vignettes/interactions.html">Interactions, polynomials, and splines</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/get_started.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Get started</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Tutorials</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/predictions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predictions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparisons</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Slopes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/hypothesis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/plot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Plots</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Case studies</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bayes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/bootstrap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bootstrap &amp; Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Categorical outcomes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/conformal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conformal prediction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/conjoint.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conjoint experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/elasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Elasticity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/equivalence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Equivalence Tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Experiments</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/gam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GAM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/gcomputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">G-Computation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/heterogeneity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Heterogeneity</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Interactions, polynomials, and splines</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/ipw.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inverse Probability Weighting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/logit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Logit</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/lme4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mixed Effects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/machine_learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Machine Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/marginalmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Marginal Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Matching</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/mrp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MrP</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/multiple_imputation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Missing Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/svalues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">S Values</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Miscellaneous</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/help.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Help</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/faq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">FAQ</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/meme.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Meme gallery</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/alternative_software.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Alternative Software</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/extensions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extensions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/links.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Links</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/numpyro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">NumPyro</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/supported_models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Supported Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../vignettes/uncertainty.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Standard Errors</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Functions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/predictions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>predictions</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>comparisons</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>slopes</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/plot_predictions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>plot_predictions</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/plot_comparisons.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>plot_comparisons</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/plot_slopes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>plot_slopes</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>hypotheses</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/inferences.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>inferences</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/posterior_draws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>posterior_draws</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/datagrid.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>datagrid</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../man/print.marginaleffects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><code>print.marginaleffects</code></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../NEWS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">News</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../LICENSE.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">License</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../CITATION.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Citation</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#multiplicative-interactions" id="toc-multiplicative-interactions" class="nav-link active" data-scroll-target="#multiplicative-interactions">Multiplicative interactions</a>
  <ul class="collapse">
<li><a href="#categorical-by-categorical" id="toc-categorical-by-categorical" class="nav-link" data-scroll-target="#categorical-by-categorical">Categorical-by-categorical</a></li>
  <li><a href="#categorical-by-continuous" id="toc-categorical-by-continuous" class="nav-link" data-scroll-target="#categorical-by-continuous">Categorical-by-continuous</a></li>
  <li><a href="#continuous-by-continuous" id="toc-continuous-by-continuous" class="nav-link" data-scroll-target="#continuous-by-continuous">Continuous-by-continuous</a></li>
  <li><a href="#multiple-interactions" id="toc-multiple-interactions" class="nav-link" data-scroll-target="#multiple-interactions">Multiple interactions</a></li>
  <li><a href="#hypothesis-tests-effect-vs.-moderation" id="toc-hypothesis-tests-effect-vs.-moderation" class="nav-link" data-scroll-target="#hypothesis-tests-effect-vs.-moderation">Hypothesis tests: effect vs.&nbsp;moderation</a></li>
  </ul>
</li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression">Polynomial regression</a></li>
  <li><a href="#splines" id="toc-splines" class="nav-link" data-scroll-target="#splines">Splines</a></li>
  <li><a href="#sec-interactions_simulation" id="toc-sec-interactions_simulation" class="nav-link" data-scroll-target="#sec-interactions_simulation">Data simulation</a></li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../vignettes/brms.html">Case studies</a></li><li class="breadcrumb-item"><a href="../vignettes/interactions.html">Interactions, polynomials, and splines</a></li></ol></nav><div class="quarto-title">
<h1 class="title">Interactions, polynomials, and splines</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>So far, the models that we have considered were relatively simple. In this chapter, we apply the same workflow, framework, and software introduced in Parts I and II of the book to interpret estimates from sligthly more complex specifications. Our goal is to address two related issues: heterogeneity and flexibility.</p>
<p>Heterogeneity is present in virtually all empirical domains, when the effect of an intervention is stronger in some groups or contexts. For instance, a new treatment might significantly reduce blood pressure in younger adults, but have a weaker effect on older ones. Or a marketing campaign may increase sales in rural areas but not urban ones. This chapter shows how to use <code>marginaleffects</code> to report strata-specific effects, gauge if the impact of a variable is moderated by another, and gain a deeper understanding of context conditionality.</p>
<p>Flexible statistical models can be useful when studying the complex (potentially non-linear) relationships which are common in many fields.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> In environmental science, for example, the relationship between temperature and crop yield is often non-linear: as temperatures rise, crop yields may initially increase due to optimal growing conditions but eventually decline as heat stress becomes detrimental. This chapter shows how the same toolkit used to study heterogeneity can be leveraged to develop insight about complex empirical patterns.</p>
<p>We will focus on three strategies to account for heterogeneity and increase the flexibility of our models: multiplicative interactions, polynomials, and splines.</p>
<section id="multiplicative-interactions" class="level2"><h2 class="anchored" data-anchor-id="multiplicative-interactions">Multiplicative interactions</h2>
<p>We say that there is heterogeneity when the strength of the association between an explanator <span class="math inline">\(X\)</span> and an outcome <span class="math inline">\(Y\)</span> varies based on the value of a moderator <span class="math inline">\(M\)</span>. Typically, <span class="math inline">\(M\)</span> is a variable which measures contextual elements, or characteristics of the individuals, groups, or units under observation. The key characteristic of a moderator is that it modifies the nature of the relationship between two other variables. <span class="math inline">\(M\)</span> can strengthen, weaken, or even reverse the association between an independent variable <span class="math inline">\(X\)</span> and the dependent variable <span class="math inline">\(Y\)</span>.</p>
<p>One common strategy to study moderation is to fit a statistical model with multiplicative interactions <span class="citation" data-cites="BraClaGol2006 KamFra2009 ClaGol2023">[@BraClaGol2006; @KamFra2009; @ClaGol2023]</span>. This involves creating a new composite variable by multiplying the explanator (<span class="math inline">\(X\)</span>) to the moderator (<span class="math inline">\(M\)</span>). When this composite variable is included in the model specification, its associated coefficient will capture <span class="math inline">\(M\)</span>’s role in effect modification. A popular specification for moderation analysis is this linear model:<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p><span class="math display">\[Y = \beta_1 + \beta_2 \cdot M + \beta_3 \cdot X + \beta_4 \cdot X \cdot  M + \varepsilon,\]</span></p>
<p>where <span class="math inline">\(Y\)</span> is the outcome, <span class="math inline">\(X\)</span> is the cause of interest, and <span class="math inline">\(M\)</span> is a contextual variable which moderates the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. In that model, <span class="math inline">\(\beta_2\)</span> characterizes the association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> when <span class="math inline">\(M=0\)</span>. If the moderator <span class="math inline">\(M\)</span> is non-zero, the strength of association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is represented by more than the simple <span class="math inline">\(\beta_2\)</span> coefficient. We see this by inspecting the partial derivative:</p>
<p><span class="math display">\[\frac{\partial Y}{\partial X} = \beta_3 + \beta_4 \cdot M\]</span></p>
<p>This equation represents the slope of <span class="math inline">\(Y\)</span> with respect to <span class="math inline">\(X\)</span>, that is, the extent to which <span class="math inline">\(Y\)</span> is expected to change in response to a small change in <span class="math inline">\(X\)</span>. Clearly, this relationship now depends on more than just <span class="math inline">\(X\)</span> itself: the strength of association between <span class="math inline">\(X\)</span> on <span class="math inline">\(Y\)</span> is driven in part by the value of <span class="math inline">\(M\)</span>. Thusly, this model specification allows the effect of an explanator to vary based on the value of a mediator.</p>
<p>In the next few sections, we will illustrate how to model heterogeneity using multiplicative interactions and how to interpret our parameter estimates using the software tools and conceptual framework in Parts I and II.</p>
<section id="categorical-by-categorical" class="level3"><h3 class="anchored" data-anchor-id="categorical-by-categorical">Categorical-by-categorical</h3>
<p>The first case to consider is when the association between a categorical explanator <code>X</code> and an outcome <code>Y</code> is moderated by a categorical variable <code>M</code>. This situation could occur when the effect of a binary treatment (treatment vs.&nbsp;control) on patient recovery (outcome) varies across different age groups (young, middle-aged, elderly).</p>
<p>To illustrate, we consider simulated data (<a href="#sec-interactions_simulation" class="quarto-xref">Section&nbsp;4</a>) with three variables: the outcome <code>Y</code> is a binary variable; the treatment <code>X</code> is a binary variable; and the moderator <code>M</code> is a categorical variable with 3 levels (a, b, and c).</p>
<p>We load the data and fit a logistic regression model:<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://marginaleffects.com/">marginaleffects</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/interaction_01.csv"</span><span class="op">)</span></span>
<span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M</span>, data <span class="op">=</span> <span class="va">dat</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As is the case for many of the more complex models that we will consider, the coefficient estimates for this logit model with interactions are difficult to interpret on their own:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; glm(formula = Y ~ X * M, family = binomial, data = dat)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; (Intercept)  0.43643    0.07195   6.065 1.32e-09 ***</span></span>
<span><span class="co">#&gt; X            0.26039    0.10337   2.519   0.0118 *  </span></span>
<span><span class="co">#&gt; Mb           0.56596    0.10699   5.290 1.23e-07 ***</span></span>
<span><span class="co">#&gt; Mc           0.96967    0.11087   8.746  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; X:Mb         0.89492    0.17300   5.173 2.30e-07 ***</span></span>
<span><span class="co">#&gt; X:Mc         1.41219    0.21462   6.580 4.71e-11 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; (Dispersion parameter for binomial family taken to be 1)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Null deviance: 5284.2  on 4999  degrees of freedom</span></span>
<span><span class="co">#&gt; Residual deviance: 4808.5  on 4994  degrees of freedom</span></span>
<span><span class="co">#&gt; AIC: 4820.5</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Fisher Scoring iterations: 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Thankfully, we can rely on the framework and tools introduced in Parts I and II of this book to make these results intelligible.</p>
<section id="marginal-predictions" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="marginal-predictions">Marginal predictions</h4>
<p>Our first cut is to compute the average predicted outcome for each combination of <code>X</code> and <code>M</code>. As explained in <strong>?@sec-predictions</strong>, this is equivalent to computing fitted values for every row in the original data, and then aggregating those fitted values by subgroups.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/predictions.html">avg_predictions</a></span><span class="op">(</span><span class="va">mod</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X"</span>, <span class="st">"M"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  X M Estimate Std. Error     z Pr(&gt;|z|)     S 2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;  0 a    0.607    0.01716  35.4   &lt;0.001 909.5 0.574  0.641</span></span>
<span><span class="co">#&gt;  1 b    0.896    0.01058  84.7   &lt;0.001   Inf 0.876  0.917</span></span>
<span><span class="co">#&gt;  0 c    0.803    0.01334  60.2   &lt;0.001   Inf 0.777  0.829</span></span>
<span><span class="co">#&gt;  1 a    0.667    0.01647  40.5   &lt;0.001   Inf 0.635  0.700</span></span>
<span><span class="co">#&gt;  0 b    0.732    0.01555  47.0   &lt;0.001   Inf 0.701  0.762</span></span>
<span><span class="co">#&gt;  1 c    0.956    0.00707 135.2   &lt;0.001   Inf 0.942  0.970</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: rowid, X, M, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, rowid_dedup</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There is considerable variation in the predicted value of <code>Y</code> across subgroups, going from 61% to 96%. This variation can be made starker by plotting our results with the <code><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M"</span>, <span class="st">"X"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions_predictions_bin_cat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions_predictions_bin_cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions_predictions_bin_cat-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions_predictions_bin_cat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Average predicted probability that Y=1 for different values of M and X.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-interactions_predictions_bin_cat" class="quarto-xref">Figure&nbsp;1</a> shows that, on average, the predicted probability that <code>Y=1</code> is considerably higher when <code>X=1</code>. Moreover, the difference in predicted outcomes <span class="math inline">\(P(Y=1|X=1,M=a)-P(Y=1|X=0,M=a)\)</span> seems smaller than <span class="math inline">\(P(Y=1|X=1,M=c)-P(Y=1|X=0,M=c)\)</span>. This is a hint that we may want to formally check for effect moderation.</p>
</section><section id="does-x-affect-y" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="does-x-affect-y">Does <code>X</code> affect <code>Y</code>?</h4>
<p>We can build on these preliminary findings by adopting a more explicitly counterfactual approach, using the <code><a href="https://marginaleffects.com/man/comparisons.html">comparisons()</a></code> family of function. Recall, from <strong>?@sec-comparisons</strong>, that we can compute an average counterfactual comparison by following these steps:</p>
<ol type="1">
<li>Modify the original dataset by fixing <code>X</code> to 0 for all observations, and compute predictions for every row.</li>
<li>Modify the original dataset by fixing <code>X</code> to 1 for all observations, and compute predictions for every row.</li>
<li>Calculate the average difference between counterfactual predictions computed in steps 1 and 2.</li>
</ol>
<p>These three steps can be taken with a single line of code:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     0.127     0.0112 11.3   &lt;0.001 96.0 0.105  0.149</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On average, moving from 0 to 1 on the <code>X</code> variable is associated with an increase of 0.127 on the outcome scale. Since we fit a logistic regression model, predictions are expressed on the probability scale. Thus, the estimate printed above suggests that the average treatment effect of <code>X</code> on <code>Y</code> is about 12.7 percentage points. This estimate is statistically distinguishable from zero, as the small <span class="math inline">\(p\)</span> value attests.</p>
</section><section id="is-the-effect-of-x-on-y-moderated-by-m" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="is-the-effect-of-x-on-y-moderated-by-m">Is the effect of <code>X</code> on <code>Y</code> moderated by <code>M</code>?</h4>
<p>Now we can dive deeper, exploiting the multiplicative interaction in our model to interrogate heterogeneity. To see if the effect of <code>X</code> on <code>Y</code> depends on <code>M</code>, we make the same function call as above, but add the <code>by</code> argument:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, by <span class="op">=</span> <span class="st">"M"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  M Estimate Std. Error     z Pr(&gt;|z|)    S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;  a   0.0601     0.0238  2.53   0.0115  6.4 0.0135  0.107</span></span>
<span><span class="co">#&gt;  b   0.1649     0.0188  8.77   &lt;0.001 58.9 0.1280  0.202</span></span>
<span><span class="co">#&gt;  c   0.1529     0.0151 10.13   &lt;0.001 77.7 0.1233  0.182</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, M, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On average, moving from the control (<code>X=0</code>) to the treatment group (<code>X=1</code>) is associated with an increase of 6 percentage points for individuals in category A. The average estimated effect of <code>X</code> for individuals in category C is 15.</p>
<p>At first glance, these two estimated effects look different. But is the difference between 6 and 15 percentage points statistically significant? To answer this question, we can use the <code>hypothesis</code> argument and conduct a test of equality between the 1st and the 3rd estimate:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, by <span class="op">=</span> <span class="st">"M"</span>, hypothesis <span class="op">=</span> <span class="st">"b3 - b1 = 0"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;    0.0928     0.0282 3.29   &lt;0.001 10.0 0.0376  0.148</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b3-b1=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The difference between the average estimated effect of <code>X</code> in categories C and A is: <span class="math inline">\(0.1529 - 0.0601 = 0.0928\)</span>. This difference is associated to a large <span class="math inline">\(z\)</span> statistic and a small <span class="math inline">\(p\)</span> value. Therefore, we can conclude that the difference is statistically significant; we can reject the null hypothesis that the effect of <code>X</code> is the same in sub-populations A and C.</p>
</section></section><section id="categorical-by-continuous" class="level3"><h3 class="anchored" data-anchor-id="categorical-by-continuous">Categorical-by-continuous</h3>
<p>The second case to consider is an interaction between a categorical explanator (<code>X</code>) and a continuous mediator (<code>M</code>). To illustrate, we fit a new model to simulated data (see <a href="#sec-interactions_simulation" class="quarto-xref">Section&nbsp;4</a>):</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/interaction_02.csv"</span><span class="op">)</span></span>
<span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M</span>, data <span class="op">=</span> <span class="va">dat</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; glm(formula = Y ~ X * M, family = binomial, data = dat)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; (Intercept) -0.83981    0.04644 -18.083  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; X            0.19222    0.06334   3.035  0.00241 ** </span></span>
<span><span class="co">#&gt; M           -0.75891    0.05049 -15.030  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; X:M          0.35209    0.06753   5.213 1.85e-07 ***</span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; (Dispersion parameter for binomial family taken to be 1)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Null deviance: 6367.0  on 4999  degrees of freedom</span></span>
<span><span class="co">#&gt; Residual deviance: 6011.4  on 4996  degrees of freedom</span></span>
<span><span class="co">#&gt; AIC: 6019.4</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Fisher Scoring iterations: 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="conditional-predictions" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="conditional-predictions">Conditional predictions</h4>
<p>In the previous section, we started by compute average predictions for each combination of the interacted variable. When one of the variables is continuous and takes on many values (like <code>M</code>), it is not practical to report averages for every combination of <code>X</code> and <code>M</code>. Therefore, we focus on “conditional” estimates, obtained by calling the <code><a href="https://marginaleffects.com/man/predictions.html">predictions()</a></code> function. We use the <code><a href="https://marginaleffects.com/man/datagrid.html">datagrid()</a></code> and <code><a href="https://rdrr.io/r/stats/fivenum.html">fivenum()</a></code> functions to create a grid of predictors based on Tukey’s five number summary of <code>M</code>:<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/predictions.html">predictions</a></span><span class="op">(</span><span class="va">mod</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, M <span class="op">=</span> <span class="va">fivenum</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  X        M Estimate Pr(&gt;|z|)     S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;  0 -3.14813   0.8248   &lt;0.001  75.9 0.7766 0.8645</span></span>
<span><span class="co">#&gt;  0 -0.65902   0.4159   &lt;0.001  35.8 0.3921 0.4401</span></span>
<span><span class="co">#&gt;  0  0.00407   0.3009   &lt;0.001 241.6 0.2821 0.3204</span></span>
<span><span class="co">#&gt;  0  0.68359   0.2045   &lt;0.001 329.8 0.1848 0.2256</span></span>
<span><span class="co">#&gt;  0  3.53494   0.0287   &lt;0.001 240.8 0.0198 0.0414</span></span>
<span><span class="co">#&gt;  1 -3.14813   0.6532   &lt;0.001  16.6 0.5871 0.7139</span></span>
<span><span class="co">#&gt;  1 -0.65902   0.4063   &lt;0.001  45.3 0.3830 0.4300</span></span>
<span><span class="co">#&gt;  1  0.00407   0.3432   &lt;0.001 168.1 0.3244 0.3624</span></span>
<span><span class="co">#&gt;  1  0.68359   0.2838   &lt;0.001 206.5 0.2623 0.3063</span></span>
<span><span class="co">#&gt;  1  3.53494   0.1105   &lt;0.001 114.7 0.0820 0.1473</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  invlink(link) </span></span>
<span><span class="co">#&gt; Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, X, M, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The results show considerable variation in the predicted <span class="math inline">\(Pr(Y=1)\)</span>, ranging from 0.0 to 0.8.</p>
<p>Instead of making predictions for discrete values of the continuous moderator <code>M</code>, we can also draw a plot with that variable on the x-axis:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod</span>, condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M"</span>, <span class="st">"X"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions-plot_predictions_num_bin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions-plot_predictions_num_bin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions-plot_predictions_num_bin-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions-plot_predictions_num_bin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Predicted probability that Y=1, for different values of X and M
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-interactions-plot_predictions_num_bin" class="quarto-xref">Figure&nbsp;2</a> shows that predicted values of <code>Y</code> tend to be lower when <code>M</code> is large. That figure also suggests that the relationship between <code>X</code> and <code>Y</code> has a different character for different values of <span class="math inline">\(M\)</span>. When <span class="math inline">\(M\)</span> is small, we see <span class="math inline">\(Pr(Y=1|X=1)&lt;Pr(Y=1|X=0)\)</span>. When <span class="math inline">\(M\)</span> is large, the converse seems true.</p>
</section><section id="does-x-affect-y-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="does-x-affect-y-1">Does <code>X</code> affect <code>Y</code>?</h4>
<p>Moving to the counterfactual analysis, we call <code><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons()</a></code> to get an overall estimate of the effect of <code>X</code> on the predicted <span class="math inline">\(Pr(Y=1)\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)   S   2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;    0.0284     0.0129 2.21   0.0273 5.2 0.00318 0.0536</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On average, moving from 0 to 1 on <code>X</code> increases the predicted probability that <code>Y=1</code> by 2.8 percentage points.</p>
</section><section id="is-the-effect-of-x-on-y-moderated-by-m-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="is-the-effect-of-x-on-y-moderated-by-m-1">Is the effect of <code>X</code> on <code>Y</code> moderated by <code>M</code>?</h4>
<p>As explained in <strong>?@sec-comparisons</strong>, we can estimate the effect of <code>X</code> for different values of <code>M</code> by using the <code>newdata</code> argument and <code><a href="https://marginaleffects.com/man/datagrid.html">datagrid()</a></code> function. Here, we measure the strength of association between <code>X</code> and <code>Y</code> for two different values of <code>M</code>: its minimum and maximum.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">range</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;      M Estimate Std. Error     z Pr(&gt;|z|)    S   2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;  -3.15  -0.1716     0.0395 -4.35   &lt;0.001 16.2 -0.2489 -0.0943</span></span>
<span><span class="co">#&gt;   3.53   0.0818     0.0174  4.70   &lt;0.001 18.5  0.0477  0.1159</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: 1 - 0</span></span>
<span><span class="co">#&gt; Columns: rowid, term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, M, predicted_lo, predicted_hi, predicted, X, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Moving from 0 to 1 on the <code>X</code> variable is associated with a change of -0.172 in the predicted <code>Y</code> when the moderator <code>M</code> is at its minimum. Moving from 0 to 1 on the <code>X</code> variable is associated with a change of 0.082 in the predicted <code>Y</code> when the moderator <code>M</code> is at its maximum. Both of these estimates are associated with small <span class="math inline">\(p\)</span> values, so we can reject the null hypotheses that they are equal to zero.</p>
<p>Both estimates are different from zero, but are they different from one another? Is the effect of <code>X</code> on <code>Y</code> different when <code>M</code> takes on different values? To check this, we can add the <code>hypothesis</code> argument to the previous call:</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>  hypothesis <span class="op">=</span> <span class="st">"b2 - b1 = 0"</span>,</span>
<span>  variables <span class="op">=</span> <span class="st">"X"</span>,</span>
<span>  newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">range</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     0.253     0.0546 4.64   &lt;0.001 18.2 0.146   0.36</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b2-b1=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This confirms that the estimates are statistically distinguishable. We can reject the null hypothesis that <code>M</code> has no moderating effect the relationship between <code>X</code> and <code>Y</code>.</p>
</section></section><section id="continuous-by-continuous" class="level3"><h3 class="anchored" data-anchor-id="continuous-by-continuous">Continuous-by-continuous</h3>
<p>The third case to consider is an interaction between two continuous numeric variables: <code>X</code> and <code>M</code>. To illustrate, we fit a new model to simulated data (see <a href="#sec-interactions_simulation" class="quarto-xref">Section&nbsp;4</a>):</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/interaction_03.csv"</span><span class="op">)</span></span>
<span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M</span>, data <span class="op">=</span> <span class="va">dat</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="conditional-predictions-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="conditional-predictions-1">Conditional predictions</h4>
<p>As in the previous cases, we begin by computing the predicted outcomes for different values of the predictors. In practice, the analyst should report predictions for predictor values that are meaningful to the domain of application. Here, we hold <code>X</code> and <code>M</code> to fixed arbitrary values:</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/predictions.html">predictions</a></span><span class="op">(</span><span class="va">mod</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">2</span>, <span class="fl">2</span><span class="op">)</span>, M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;   X  M Estimate Pr(&gt;|z|)     S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;  -2 -1   0.2586   &lt;0.001  78.0 0.2215 0.2995</span></span>
<span><span class="co">#&gt;  -2  0   0.1365   &lt;0.001 380.2 0.1189 0.1563</span></span>
<span><span class="co">#&gt;  -2  1   0.0669   &lt;0.001 326.1 0.0531 0.0839</span></span>
<span><span class="co">#&gt;   2 -1   0.2177   &lt;0.001 104.1 0.1837 0.2561</span></span>
<span><span class="co">#&gt;   2  0   0.4855    0.425   1.2 0.4500 0.5212</span></span>
<span><span class="co">#&gt;   2  1   0.7619   &lt;0.001  87.2 0.7213 0.7982</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  invlink(link) </span></span>
<span><span class="co">#&gt; Columns: rowid, estimate, p.value, s.value, conf.low, conf.high, X, M, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rather than focus on arbitrary point estimates, we can plot predicted values to communicate a richer set of estimates. When calling <code><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions()</a></code> with these data, we obtain a plot of predicted outcomes with the primary variable of interest (<code>X</code>) on the x-axis, and different lines representing different values of the moderator (<code>M</code>).</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod</span>, condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X"</span>, <span class="st">"M"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions_plot_predictions_num_num" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions_plot_predictions_num_num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions_plot_predictions_num_num-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions_plot_predictions_num_num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Predicted value of Y for different values of X and M
</figcaption></figure>
</div>
</div>
</div>
<p>We can draw two preliminary conclusions from <a href="#fig-interactions_plot_predictions_num_num" class="quarto-xref">Figure&nbsp;3</a>. First, the predicted values of <code>Y</code> depend strongly on the value of <code>X</code>. Moving from left to right in the plot often has a strong effect on the heights of predicted probability curves. Second, <code>M</code> strongly moderates the relationship between <code>X</code> and <code>Y</code>. Indeed, for some values of <code>M</code> the relationship of interest completely flips. For example, when <code>M</code> is around -3, the relationship between <code>X</code> and <code>Y</code> is negative: an increase in <code>X</code> is associated with a decrease in <code>Pr(Y=1)</code>. However, for all the other values of <code>M</code> that we considered, the relationship between <code>X</code> and <code>Y</code> is positive: an increase in <code>X</code> is associated withn an increase in <code>Pr(Y=1)</code>.</p>
</section><section id="does-x-affect-y-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="does-x-affect-y-2">Does <code>X</code> affect <code>Y</code>?</h4>
<p>To measure the “effect” of <code>X</code> on the predicted outcome, we can compute the average slope with respect to our predictor of interest:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">avg_slopes</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error  z Pr(&gt;|z|)     S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;    0.0857    0.00571 15   &lt;0.001 166.7 0.0745 0.0969</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(dY/dX)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>On average, across all observed values of the moderator <code>M</code>, increasing <code>X</code> by one unit increases the predicted outcome by 0.086.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a> This is interesting, but as suggested by <a href="#fig-interactions_plot_predictions_num_num" class="quarto-xref">Figure&nbsp;3</a>, there is strong heterogeneity in the relationship of interest, as a function of moderator <code>M</code>. Indeed, this is what we observe by computing slopes for different values of <code>M</code>:</p>
</section><section id="is-the-effect-of-x-on-y-moderated-by-m-2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="is-the-effect-of-x-on-y-moderated-by-m-2">Is the effect of <code>X</code> on <code>Y</code> moderated by <code>M</code>?</h4>
<p>To answer this question, we estimate slopes of <code>Y</code> with respect to <code>X</code>, for different values of the moderator <code>M</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">slopes</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">fivenum</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;        M Estimate Std. Error     z Pr(&gt;|z|)     S    2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;  -3.0788  -0.1525    0.01899 -8.03  &lt; 0.001  49.9 -0.18969 -0.1153</span></span>
<span><span class="co">#&gt;  -0.6759   0.0200    0.00756  2.65  0.00816   6.9  0.00519  0.0348</span></span>
<span><span class="co">#&gt;   0.0137   0.0913    0.00695 13.14  &lt; 0.001 128.7  0.07768  0.1049</span></span>
<span><span class="co">#&gt;   0.6906   0.1698    0.00950 17.86  &lt; 0.001 234.7  0.15113  0.1884</span></span>
<span><span class="co">#&gt;   3.4711   0.5426    0.03363 16.14  &lt; 0.001 192.2  0.47673  0.6085</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, M, predicted_lo, predicted_hi, predicted, X, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The results from this command confirm the intuition we developed based on <a href="#fig-interactions_plot_predictions_num_num" class="quarto-xref">Figure&nbsp;3</a>. When <code>M</code> is strongly negative (-3), the slope is negative: increasing <code>X</code> results in a reduction of <code>Y</code>. However, for the other 4 values of <code>M</code> we consider, the slope is positive. This is consistent with <a href="#fig-interactions_plot_predictions_num_num" class="quarto-xref">Figure&nbsp;3</a>, which shows one line with downward slope, and four lines with upward slopes.</p>
<p>For a more fine grained analysis, we can plot the slope of <code>Y</code> with respect to <code>X</code> for all observed values of the moderator <code>M</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/plot_slopes.html">plot_slopes</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, condition <span class="op">=</span> <span class="st">"M"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span><span class="op">(</span>yintercept <span class="op">=</span> <span class="fl">0</span>, linetype <span class="op">=</span> <span class="st">"dotted"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions_plot_slopes_num_num" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions_plot_slopes_num_num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions_plot_slopes_num_num-1.png" class="img-fluid figure-img" width="576">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions_plot_slopes_num_num-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Slope of <code>Y</code> with respect to <code>X</code>, for different values of the moderator <code>M</code>.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-interactions_plot_slopes_num_num" class="quarto-xref">Figure&nbsp;4</a> plot shows that when the moderator <code>M</code> is below -1, the relationship between <code>X</code> and <code>Y</code> is negative: increasing <code>X</code> decreases <code>Y</code>. However, when <code>M</code> rises to about -1, the relationship between <code>X</code> and <code>Y</code> becomes positive: increasing <code>X</code> increases <code>Y</code>.</p>
<p>We can confirm that this moderation effect is statistically significant using the <code>hypothesis</code> argument:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">slopes</a></span><span class="op">(</span><span class="va">mod</span>,</span>
<span>  hypothesis <span class="op">=</span> <span class="st">"b2 - b1 = 0"</span>, </span>
<span>  variables <span class="op">=</span> <span class="st">"X"</span>,</span>
<span>  newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="va">range</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)     S 2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     0.695     0.0475 14.6   &lt;0.001 158.8 0.602  0.788</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b2-b1=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <span class="math inline">\(\frac{\partial Y}{\partial X}\)</span> slope is larger when evaluated at maximum <code>M</code>, than at minimum <code>M</code>. Therefore, we can reject the null hypothesis that <code>M</code> has no moderating effect on the relationship between <code>X</code> and <code>Y</code>.</p>
</section></section><section id="multiple-interactions" class="level3"><h3 class="anchored" data-anchor-id="multiple-interactions">Multiple interactions</h3>
<p>The fourth case to consider is when more than two variables are included in multiplicative interactions. Such models have serious downsides: they can overfit the data, and they impose major costs in terms of statistical power, typically requiring considerably larger sample sizes than models without interaction. On the upside, models with multiple interactions allow more flexibility in modelling, and they can capture complex patterns of moderation between regressors.</p>
<p>Models with several multiplicative interactions do not pose any particular interpretation challenge, since the tools and workflows introduced in this book can be applied to these models in straightforward fashion. Consider this model, fit to simulated data, with three binary variables multipled to each other:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/interaction_04.csv"</span><span class="op">)</span></span>
<span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/glm.html">glm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M1</span> <span class="op">*</span> <span class="va">M2</span>, data <span class="op">=</span> <span class="va">dat</span>, family <span class="op">=</span> <span class="va">binomial</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mod</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Call:</span></span>
<span><span class="co">#&gt; glm(formula = Y ~ X * M1 * M2, family = binomial, data = dat)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Coefficients:</span></span>
<span><span class="co">#&gt;             Estimate Std. Error z value Pr(&gt;|z|)    </span></span>
<span><span class="co">#&gt; (Intercept)  -1.0209     0.0908 -11.244  &lt; 2e-16 ***</span></span>
<span><span class="co">#&gt; X             0.4632     0.1229   3.768 0.000165 ***</span></span>
<span><span class="co">#&gt; M1           -0.7954     0.1470  -5.411 6.26e-08 ***</span></span>
<span><span class="co">#&gt; M2            0.5788     0.1217   4.755 1.98e-06 ***</span></span>
<span><span class="co">#&gt; X:M1          0.6746     0.1890   3.569 0.000358 ***</span></span>
<span><span class="co">#&gt; X:M2         -0.9649     0.1716  -5.623 1.87e-08 ***</span></span>
<span><span class="co">#&gt; M1:M2         0.4046     0.1890   2.141 0.032297 *  </span></span>
<span><span class="co">#&gt; X:M1:M2       0.1976     0.2542   0.777 0.436869    </span></span>
<span><span class="co">#&gt; ---</span></span>
<span><span class="co">#&gt; Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; (Dispersion parameter for binomial family taken to be 1)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;     Null deviance: 6176.5  on 4999  degrees of freedom</span></span>
<span><span class="co">#&gt; Residual deviance: 6025.2  on 4992  degrees of freedom</span></span>
<span><span class="co">#&gt; AIC: 6041.2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Number of Fisher Scoring iterations: 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Once again, the coefficient estimates of this logistic regression are difficult to interpret on their own, so we use functions from the <code>marginaleffects</code> package.</p>
<section id="marginal-predictions-1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="marginal-predictions-1">Marginal predictions</h4>
<p>As before, we can compute and display marginal predicted outcomes in any subgroup of interest, using the <code><a href="https://marginaleffects.com/man/predictions.html">avg_predictions()</a></code> or <code><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X"</span>, <span class="st">"M1"</span>, <span class="st">"M2"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions_plot_predictions_multiple" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions_plot_predictions_multiple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions_plot_predictions_multiple-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions_plot_predictions_multiple-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Average predicted outcomes for different combinations of <code>X</code>, <code>M1</code>, and <code>M2</code>.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="does-x-affect-y-3" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="does-x-affect-y-3">Does <code>X</code> affect <code>Y</code>?</h4>
<p>As before, we can estimate the average change in <code>Y</code> associated with a change from 0 to 1 in the <code>X</code> variable using the <code><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons()</a></code> function:</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error   z Pr(&gt;|z|)    S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;    0.0657     0.0129 5.1   &lt;0.001 21.5 0.0405  0.091</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This suggests that, on average, moving from the control (0) to the treatment (1) group is associated with an increase of 6.6 percentage points in the probability that <code>Y</code> equals 1. The <span class="math inline">\(p\)</span> value is small, which implies that we can reject the null hypothesis that <code>X</code> has no effect on the predicted outcome.</p>
</section><section id="is-the-effect-of-x-on-y-moderated-by-m1" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="is-the-effect-of-x-on-y-moderated-by-m1">Is the effect of <code>X</code> on <code>Y</code> moderated by <code>M1</code>?</h4>
<p>We can also estimate how the effect of <code>X</code> varies based on different values of moderator <code>M1</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, by <span class="op">=</span> <span class="st">"M1"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  M1 Estimate Std. Error     z Pr(&gt;|z|)    S   2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;   0 -0.00703     0.0185 -0.38    0.704  0.5 -0.0433 0.0292</span></span>
<span><span class="co">#&gt;   1  0.14026     0.0179  7.83   &lt;0.001 47.6  0.1052 0.1754</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, M1, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The results suggest that the change in <code>Y</code> associated with a change in <code>X</code> differs based on the value of <code>M1</code>: -0.0070 vs.&nbsp;0.1403. By using the <code>hypothesis</code> argument, we can confirm that the difference between these two estimated effect sizes is statistically significant:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>  variables <span class="op">=</span> <span class="st">"X"</span>,</span>
<span>  by <span class="op">=</span> <span class="st">"M1"</span>,</span>
<span>  hypothesis <span class="op">=</span> <span class="st">"b2 - b1 = 0"</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)    S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     0.147     0.0258 5.72   &lt;0.001 26.5 0.0968  0.198</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b2-b1=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="does-the-moderating-effect-of-m1-depend-on-m2" class="level4 unnumbered"><h4 class="unnumbered anchored" data-anchor-id="does-the-moderating-effect-of-m1-depend-on-m2">Does the moderating effect of <code>M1</code> depend on <code>M2</code>?</h4>
<p>The last question that we pose is more complex. Above, we established that:</p>
<ol type="1">
<li>On average, <code>X</code> affects the predicted value of <code>Y</code>.</li>
<li>On average, the value of <code>M1</code> modifies the strength of association between <code>X</code> and <code>Y</code>.</li>
</ol>
<p>Now we ask if <code>M2</code> changes the way in which <code>M1</code> moderates the effect of <code>X</code> on <code>Y</code>. The difference is subtle but important: we are asking if the moderation effect of <code>M1</code> is itself moderated by <code>M2</code>.</p>
<p>The following code computes the average difference in predicted <code>Y</code> associated with a change in <code>X</code>, for every combination of moderators <code>M1</code> and <code>M2</code>. Each row represents the average effect of <code>X</code> at different points in the sample space:</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>    variables <span class="op">=</span> <span class="st">"X"</span>, </span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M2"</span>, <span class="st">"M1"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  M2 M1 Estimate Std. Error     z Pr(&gt;|z|)    S   2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;   0  0   0.0992     0.0261  3.80  &lt; 0.001 12.8  0.0481  0.1504</span></span>
<span><span class="co">#&gt;   0  1   0.1967     0.0236  8.35  &lt; 0.001 53.7  0.1505  0.2429</span></span>
<span><span class="co">#&gt;   1  0  -0.1111     0.0262 -4.24  &lt; 0.001 15.4 -0.1625 -0.0597</span></span>
<span><span class="co">#&gt;   1  1   0.0834     0.0270  3.09  0.00203  8.9  0.0304  0.1363</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: X</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Comparison: mean(1) - mean(0)</span></span>
<span><span class="co">#&gt; Columns: term, contrast, M2, M1, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When we hold the moderators fixed at <code>M1=0</code> and <code>M2=0</code>, changing the value of <code>X</code> from 0 to 1 changes the predicted value of <code>Y</code> by 9.9 percentage points. When we hold the moderators fixed at <code>M1=0</code> and <code>M2=1</code>, changing the value of <code>X</code> from 0 to 1 changes the predicted value of <code>Y</code> by -11.1 percentage points.</p>
<p>Now, imagine that we hold <code>M2</code> constant at 0. We can determine if the effect of <code>X</code> is moderated by <code>M1</code> by using the <code>hypothesis</code> argument to compare estimates in rows 1 and 2. This shows that the estimated effect size of <code>X</code> is larger when <code>M1=1</code> than when <code>M1=0</code>, holding <code>M2</code> at 0.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>    hypothesis <span class="op">=</span> <span class="st">"b2 - b1 = 0"</span>,</span>
<span>    variables <span class="op">=</span> <span class="st">"X"</span>, </span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M2"</span>, <span class="st">"M1"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)   S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;    0.0975     0.0351 2.77  0.00555 7.5 0.0286  0.166</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b2-b1=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly, imagine that we hold <code>M2</code> constant at 1. We can determine if the effect of <code>X</code> is moderated by <code>M1</code> by comparing estimates in rows 3 and 4. This hypothesis test shows that the effect size of <code>X</code> is larger when <code>M1=1</code> than when <code>M1=0</code>, holding <code>M2</code> at 1.</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>    hypothesis <span class="op">=</span> <span class="st">"b4 - b3 = 0"</span>,</span>
<span>    variables <span class="op">=</span> <span class="st">"X"</span>, </span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M2"</span>, <span class="st">"M1"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error    z Pr(&gt;|z|)    S 2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     0.194     0.0377 5.16   &lt;0.001 22.0 0.121  0.268</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: b4-b3=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The last two estimates can be interpreted as measuring the extent to which <code>M1</code> acts as a moderator, holding <code>M2</code> at different values. To answer the question of whether <code>M2</code> moderates the moderation effect of <code>M1</code>, we can specify the <code>hypothesis</code> as a difference in differences:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/comparisons.html">avg_comparisons</a></span><span class="op">(</span><span class="va">mod</span>, </span>
<span>    hypothesis <span class="op">=</span> <span class="st">"(b2 - b1) - (b4 - b3) = 0"</span>,</span>
<span>    variables <span class="op">=</span> <span class="st">"X"</span>, </span>
<span>    by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"M2"</span>, <span class="st">"M1"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Estimate Std. Error     z Pr(&gt;|z|)   S  2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;    -0.097     0.0515 -1.88   0.0597 4.1 -0.198 0.00396</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Term: (b2-b1)-(b4-b3)=0</span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This suggests that <code>M2</code> <em>may</em> have a second order moderation effect, but we cannot completely completely rule out the null hypothesis because the <span class="math inline">\(p\)</span> value does not cross conventional thresholds of statistical significance (<span class="math inline">\(p\)</span>=0.0597).</p>
</section></section><section id="hypothesis-tests-effect-vs.-moderation" class="level3"><h3 class="anchored" data-anchor-id="hypothesis-tests-effect-vs.-moderation">Hypothesis tests: effect vs.&nbsp;moderation</h3>
<p>TODO: Two research questions are often conflated:</p>
<ol type="1">
<li>Effect: Does <span class="math inline">\(X\)</span> affect <span class="math inline">\(Y\)</span>?
<ul>
<li>Is the <span class="math inline">\(\frac{\partial Y}{\partial X}\)</span> slope different from 0 when <span class="math inline">\(M=m\)</span>?</li>
</ul>
</li>
<li>Moderation: Does <span class="math inline">\(M\)</span> moderate the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>?
<ul>
<li>Is the <span class="math inline">\(\frac{\partial Y}{\partial X}\)</span> different when <span class="math inline">\(M=m\)</span> and <span class="math inline">\(M=n\)</span>?</li>
</ul>
</li>
</ol></section></section><section id="polynomial-regression" class="level2"><h2 class="anchored" data-anchor-id="polynomial-regression">Polynomial regression</h2>
<p>Polynomial regression is an extension of linear regression that allows for modeling the relationship between a dependent variable <span class="math inline">\(Y\)</span> and an independent variable <span class="math inline">\(X\)</span> as an nth-degree polynomial. While the model specification remains linear in the coefficients, it is polynomial in the value of <span class="math inline">\(X\)</span>. This type of regression is useful when the data shows a non-linear relationship that a straight line cannot adequately capture.</p>
<p>The general form of a polynomial regression model is:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \beta_3 X^3 + \cdots + \beta_n X^n + \varepsilon,\]</span></p>
<p>where <span class="math inline">\(Y\)</span> is the dependent variable, <span class="math inline">\(X\)</span> is the independent variable, <span class="math inline">\(\beta_0, \beta_1, \beta_2, \ldots, \beta_n\)</span> are the coefficients to be estimated, <span class="math inline">\(n\)</span> is the degree of the polynomial, and <span class="math inline">\(\varepsilon\)</span> represents the error term. For instance, a second-degree (quadratic) polynomial regression equation can be written as:</p>
<p><span class="math display">\[Y = \beta_0 + \beta_1 X + \beta_2 X^2 + \varepsilon\]</span></p>
<p>This can be treated as a linear regression problem by constructing new variables <span class="math inline">\(Z_1=X\)</span>, <span class="math inline">\(Z_2=X^2\)</span>, etc. The model then becomes <span class="math inline">\(Y=\beta_0+\beta_1\cdot Z_1+\beta_2\cdot Z_2+\varepsilon\)</span>, which can be estimated using standard methods like ordinary least squares.</p>
<p>Polynomial regression offers several key advantages, particularly in its flexibility and ability to fit a wide range of curves, simply by adjusting the degree of the polynomial. As a result, polynomial regression can reveal underlying patterns in the data that are not immediately apparent with simpler models.</p>
<p>This approach also has notable disadvantages. One significant issue is its potential for overfitting, especially when the <span class="math inline">\(n\)</span> order is high. Moreover, polynomial regression can suffer from unreliable extrapolation, where predictions made outside the range of the training data can become erratic and unrealistic. Consequently, while polynomial regression can be powerful, careful consideration must be given to the degree of the polynomial to balance fit and generalization effectively.</p>
<p>Polynomial regression can be viewed simply as a model specification with several variables interacted with themselves. As such, it can be interpreted using exactly the same tools discussed in the earlier part of this chapter. To illustrate, we consider two simple data generating processes adapted from <span class="citation" data-cites="HaiMumXu2019">@HaiMumXu2019</span>. The first is:</p>
<p><span class="math display">\[\begin{align*}
Y = 2.5 - X^2 + \nu, &amp;&amp; \text{where }\nu\sim N(0,1),X\sim U(-3,3)
\end{align*}\]</span></p>
<p>If we fit a linear model with only <span class="math inline">\(X\)</span> as predictor, the line of best fit will not be a good representation of the data. However, a cubic polynomial regression can easily detect the curvilinear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. In <code>R</code> and <code>Python</code>, we can use similar syntax to specify polynomials directly in the model formula:<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/polynomial_01.csv"</span><span class="op">)</span></span>
<span><span class="va">mod_linear</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="va">mod_cubic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">3</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod_linear</span>, condition <span class="op">=</span> <span class="st">"X"</span>, points <span class="op">=</span> <span class="fl">.05</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Linear"</span><span class="op">)</span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod_cubic</span>, condition <span class="op">=</span> <span class="st">"X"</span>, points <span class="op">=</span> <span class="fl">.05</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Cubic"</span><span class="op">)</span></span>
<span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-interactions_polynomials" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-interactions_polynomials-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="interactions_files/figure-html/fig-interactions_polynomials-1.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-interactions_polynomials-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Modelling a curvilinear relationship with linear or polynomial regression.
</figcaption></figure>
</div>
</div>
</div>
<p>Clearly, the model with polynomials makes much better predictions, ones that capture the curvilinear relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>. We can now evaluate the strength of association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> by computing the slope of the outcome equation with respect to <span class="math inline">\(X\)</span>, for different values of <span class="math inline">\(X\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">slopes</a></span><span class="op">(</span><span class="va">mod_cubic</span>, variables <span class="op">=</span> <span class="st">"X"</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">2</span>, <span class="fl">0</span>, <span class="fl">2</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Term  X Estimate Std. Error        z Pr(&gt;|z|)   S   2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;     X -2  3.98616     0.0351  113.596   &lt;0.001 Inf  3.9174  4.0549</span></span>
<span><span class="co">#&gt;     X  0  0.00478     0.0226    0.211    0.833 0.3 -0.0396  0.0491</span></span>
<span><span class="co">#&gt;     X  2 -3.97639     0.0359 -110.705   &lt;0.001 Inf -4.0468 -3.9060</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, X, predicted_lo, predicted_hi, predicted, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When <span class="math inline">\(X\)</span> is negative (-2), the slope is positive which indicates that an increase of <span class="math inline">\(X\)</span> is associated with an increase in <span class="math inline">\(Y\)</span>. When <span class="math inline">\(X\)</span> is around 0, the slope is null, which indicates that the strength of association between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> is null (or very weak). When <span class="math inline">\(X\)</span> is around 0, changing <span class="math inline">\(X\)</span> by a small amount will have almost no effect on <span class="math inline">\(Y\)</span>. When <span class="math inline">\(X\)</span> is positive (-2), the slope is negative. This indicates that increasing <span class="math inline">\(X\)</span> will result in a decrease in <span class="math inline">\(Y\)</span>.</p>
<p>Now, consider a sligthly different data generating process, where a binary moderator <span class="math inline">\(D\)</span> changes the nature of the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>:<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
<p><span class="math display">\[\begin{align*}
Y = 2.5 - X^2 - 5 \cdot M + 2 \cdot M \cdot X^2 + \nu &amp;&amp;  \text{where }\nu\sim N(0,1),X\sim U(-3,3)
\end{align*}\]</span></p>
<p>If we simply fit a cubic regression, without accounting for <span class="math inline">\(M\)</span>, our predictions will be inaccurate. However, if we interact the moderator <span class="math inline">\(M\)</span> with all polynomial terms (using parentheses as a shortcut for the distributive property), we can get an excellent fit for the curvilinear and differentiated relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/utils/read.table.html">read.csv</a></span><span class="op">(</span><span class="st">"data/polynomial_02.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># cubic</span></span>
<span><span class="va">mod_cubic</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">X</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">3</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># cubic + interaction</span></span>
<span><span class="va">mod_cubic_int</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="va">M</span> <span class="op">*</span> <span class="op">(</span><span class="va">X</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="va">X</span><span class="op">^</span><span class="fl">3</span><span class="op">)</span><span class="op">)</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="va">p1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod_cubic</span>, condition <span class="op">=</span> <span class="st">"X"</span>, points <span class="op">=</span> <span class="fl">.05</span><span class="op">)</span></span>
<span><span class="va">p2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod_cubic_int</span>, condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X"</span>, <span class="st">"M"</span><span class="op">)</span>, points <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span></span>
<span><span class="va">p1</span> <span class="op">+</span> <span class="va">p2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="interactions_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>Of course, we can also estimate the slope of the outcome equation for different values of <code>M</code> and <code>X</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">slopes</a></span><span class="op">(</span><span class="va">mod_cubic_int</span>,</span>
<span>  variables <span class="op">=</span> <span class="st">"X"</span>,</span>
<span>  newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, X <span class="op">=</span> <span class="va">fivenum</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Term M       X Estimate Std. Error       z Pr(&gt;|z|)     S    2.5 %  97.5 %</span></span>
<span><span class="co">#&gt;     X 0 -2.9974   5.7529     0.2588  22.228   &lt;0.001 361.2  5.24566  6.2602</span></span>
<span><span class="co">#&gt;     X 0 -1.4845   2.9009     0.0582  49.874   &lt;0.001   Inf  2.78693  3.0149</span></span>
<span><span class="co">#&gt;     X 0 -0.0586   0.1324     0.0667   1.986    0.047   4.4  0.00174  0.2631</span></span>
<span><span class="co">#&gt;     X 0  1.4788  -2.9405     0.0575 -51.103   &lt;0.001   Inf -3.05323 -2.8277</span></span>
<span><span class="co">#&gt;     X 0  2.9843  -6.0373     0.2540 -23.769   &lt;0.001 412.4 -6.53517 -5.5395</span></span>
<span><span class="co">#&gt;     X 1 -2.9974  -6.1017     0.2528 -24.137   &lt;0.001 425.2 -6.59716 -5.6062</span></span>
<span><span class="co">#&gt;     X 1 -1.4845  -2.9061     0.0563 -51.628   &lt;0.001   Inf -3.01646 -2.7958</span></span>
<span><span class="co">#&gt;     X 1 -0.0586  -0.0461     0.0634  -0.727    0.467   1.1 -0.17026  0.0781</span></span>
<span><span class="co">#&gt;     X 1  1.4788   2.8730     0.0595  48.279   &lt;0.001   Inf  2.75637  2.9896</span></span>
<span><span class="co">#&gt;     X 1  2.9843   5.5654     0.2592  21.469   &lt;0.001 337.2  5.05733  6.0735</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, M, X, predicted_lo, predicted_hi, predicted, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="splines" class="level2"><h2 class="anchored" data-anchor-id="splines">Splines</h2>
<p>TODO:</p>
<ul>
<li>What is a spline?</li>
<li>What is a GAM?</li>
</ul>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">mgcv</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># mgcv::gam should treat M as categorical (factor)</span></span>
<span><span class="va">mod</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/gam.html">gam</a></span><span class="op">(</span><span class="va">Y</span> <span class="op">~</span> <span class="fu"><a href="https://rdrr.io/pkg/mgcv/man/s.html">s</a></span><span class="op">(</span><span class="va">X</span>, by <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">M</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span> <span class="va">M</span>, data <span class="op">=</span> <span class="va">dat</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://marginaleffects.com/man/plot_predictions.html">plot_predictions</a></span><span class="op">(</span><span class="va">mod</span>, condition <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"X"</span>, <span class="st">"M"</span><span class="op">)</span>, points <span class="op">=</span> <span class="fl">.1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><img src="interactions_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://marginaleffects.com/man/slopes.html">slopes</a></span><span class="op">(</span><span class="va">mod</span>, variables <span class="op">=</span> <span class="st">"X"</span>, newdata <span class="op">=</span> <span class="fu"><a href="https://marginaleffects.com/man/datagrid.html">datagrid</a></span><span class="op">(</span>M <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span>, X <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">1</span>, <span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt;  Term M  X Estimate Std. Error      z Pr(&gt;|z|)    S  2.5 % 97.5 %</span></span>
<span><span class="co">#&gt;     X 0 -1    2.134      0.212 10.087   &lt;0.001 77.1  1.719  2.548</span></span>
<span><span class="co">#&gt;     X 0  0   -0.141      0.212 -0.662    0.508  1.0 -0.557  0.276</span></span>
<span><span class="co">#&gt;     X 0  1   -1.883      0.201 -9.386   &lt;0.001 67.1 -2.276 -1.489</span></span>
<span><span class="co">#&gt;     X 1 -1   -1.879      0.201 -9.341   &lt;0.001 66.5 -2.274 -1.485</span></span>
<span><span class="co">#&gt;     X 1  0    0.113      0.215  0.526    0.599  0.7 -0.308  0.535</span></span>
<span><span class="co">#&gt;     X 1  1    2.025      0.211  9.595   &lt;0.001 70.0  1.612  2.439</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; Type:  response </span></span>
<span><span class="co">#&gt; Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, M, X, predicted_lo, predicted_hi, predicted, Y</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="sec-interactions_simulation" class="level2"><h2 class="anchored" data-anchor-id="sec-interactions_simulation">Data simulation</h2>
<p>This code generates the simulated datasets used in this chapter:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Multiplicative interactions: X x M</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">M</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/sample.html">sample</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"a"</span>, <span class="st">"b"</span>, <span class="st">"c"</span><span class="op">)</span>, <span class="va">N</span>, replace <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">8</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">*</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"b"</span><span class="op">)</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">*</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"b"</span><span class="op">)</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">5</span><span class="op">]</span> <span class="op">*</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"c"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">6</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"a"</span><span class="op">)</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">7</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"b"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">8</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="op">(</span><span class="va">M</span> <span class="op">==</span> <span class="st">"c"</span><span class="op">)</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">Y</span>, <span class="va">X</span>, <span class="va">M</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/interaction_01.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Multiplicative interactions: X x M</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">M</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">4</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">Y</span>, <span class="va">X</span>, <span class="va">M</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/interaction_02.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Multiplicative interactions: X x M</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span></span>
<span><span class="va">M</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span><span class="op">)</span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">4</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">Y</span>, <span class="va">X</span>, <span class="va">M</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/interaction_03.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Multiplicative interactions: X x M1 x M2</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">5000</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">M1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">M2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="fl">8</span>, <span class="op">-</span><span class="fl">1</span>, <span class="fl">1</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">1</span>, prob <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/Logistic.html">plogis</a></span><span class="op">(</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span> <span class="op">+</span></span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span> <span class="op">*</span> <span class="va">M1</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">4</span><span class="op">]</span> <span class="op">*</span> <span class="va">M2</span> <span class="op">+</span> </span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">5</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M1</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">6</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M2</span> <span class="op">+</span> <span class="va">b</span><span class="op">[</span><span class="fl">7</span><span class="op">]</span> <span class="op">*</span> <span class="va">M1</span> <span class="op">*</span> <span class="va">M2</span> <span class="op">+</span> </span>
<span>  <span class="va">b</span><span class="op">[</span><span class="fl">8</span><span class="op">]</span> <span class="op">*</span> <span class="va">X</span> <span class="op">*</span> <span class="va">M1</span> <span class="op">*</span> <span class="va">M2</span></span>
<span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">Y</span>, <span class="va">X</span>, <span class="va">M1</span>, <span class="va">M2</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/interaction_04.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Polynomial regression: X and Y</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">1e3</span></span>
<span><span class="va">FUN</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="fl">2.5</span> <span class="op">-</span> <span class="va">X</span><span class="op">^</span><span class="fl">2</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">N</span>, min <span class="op">=</span> <span class="op">-</span><span class="fl">3</span>, max <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fu">FUN</span><span class="op">(</span><span class="va">X</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, sd <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">X</span>, <span class="va">Y</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/polynomial_01.csv"</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Polynomial regression: X, D, and Y</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span><span class="op">(</span><span class="fl">1024</span><span class="op">)</span></span>
<span><span class="va">N</span> <span class="op">&lt;-</span> <span class="fl">1e3</span></span>
<span><span class="va">X</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Uniform.html">runif</a></span><span class="op">(</span><span class="va">N</span>, min <span class="op">=</span> <span class="op">-</span><span class="fl">3</span>, max <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span><span class="va">M</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Binomial.html">rbinom</a></span><span class="op">(</span><span class="va">N</span>, size <span class="op">=</span> <span class="fl">1</span>, prob <span class="op">=</span> <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">Y</span> <span class="op">&lt;-</span> <span class="fl">2.5</span> <span class="op">-</span> <span class="va">X</span><span class="op">^</span><span class="fl">2</span> <span class="op">-</span> <span class="fl">5</span> <span class="op">*</span> <span class="va">M</span> <span class="op">+</span> <span class="fl">2</span> <span class="op">*</span> <span class="va">M</span> <span class="op">*</span> <span class="va">X</span><span class="op">^</span><span class="fl">2</span> <span class="op">+</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="va">N</span>, <span class="fl">.5</span><span class="op">)</span></span>
<span><span class="va">dat</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">X</span>, <span class="va">M</span>, <span class="va">Y</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/write.table.html">write.csv</a></span><span class="op">(</span><span class="va">dat</span>, <span class="st">"data/polynomial_02.csv"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section><div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>
<ol>
<li id="fn1"><p>One downside of estimating more flexible models is that they may overfit the data. See TODO.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>In most cases, it is important to include all constitutive terms in addition to interactions. For example, if a model includes a multiplication between three variables <span class="math inline">\(X\cdot W \cdot Z\)</span>, one would typically want to also include <span class="math inline">\(X\cdot W, X\cdot Z, W\cdot Z, X, W,\)</span> and <span class="math inline">\(Z\)</span>. See <span class="citation" data-cites="ClaGol2023">@ClaGol2023</span> for details.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Note that when we insert an expression like <code>X*M</code> in the formula syntax, we instruct <code>R</code> to create binary variables for every level of the <code>M</code> predictor, and also to interact each of those levels with the <code>X</code> variable. Under the hood, <code>R</code> will multiply treatment and moderator to create the appropriate composite variables (<code>X</code><span class="math inline">\(\times\)</span><code>Mb</code> and <code>X</code><span class="math inline">\(\times\)</span><code>Mc</code>), and it will automatically omit one reference category to avoid perfect collinearity.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>An alternative would be to compute predictions on a different grid (ex: “balanced”) before aggregating. This could be achieved by calling: <code>avg_predictions(mod, newdata="balanced", by=c("X","M"))</code><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>These five numbers correspond to elements of a standard boxplot: minimum, lower-hinge, median, upper-hinge, and maximum.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Recall, from <strong>?@sec-slopes</strong>, that this interpretation is valid for small changes in the neighborhoods where slopes are evaluated.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>For <code>marginaleffects</code> to work properly in this context, it is important to specify the polynomials in the model-fitting formula. Users should not hard-code the values by creating new variables in the dataset before fitting the model.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>This data generating process is adapted from <span class="citation" data-cites="HaiMumXu2019">@HaiMumXu2019</span>.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></div></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="../vignettes/heterogeneity.html" class="pagination-link" aria-label="Heterogeneity">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Heterogeneity</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../vignettes/ipw.html" class="pagination-link" aria-label="Inverse Probability Weighting">
        <span class="nav-page-text">Inverse Probability Weighting</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>