---
title: "Case Studies: Bayes, Mixed-Effects, GAMs, etc."
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Case Studies: Bayes, Mixed-Effects, GAMs, etc.}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.width = 9,
  fig.asp = .4,
  out.width = "100%",
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
url <- "https://raw.githubusercontent.com/vincentarelbundock/marginaleffects/main/data-raw/supported_models.csv"
dat <- read.csv(url)
n_support <- nrow(dat)

main <- tempfile(fileext = "Rmd")
internal <- tempfile(fileext = "Rmd")
on.exit(unlink(main))
on.exit(unlink(internal))
download.file("https://raw.githubusercontent.com/vincentarelbundock/marginaleffects/main/vignettes/links_main.Rmd", main, method = "wget")
download.file("https://raw.githubusercontent.com/vincentarelbundock/marginaleffects/main/vignettes/links_internal.Rmd", internal, method = "wget")

```


[The `marginaleffects` website](https://vincentarelbundock.github.io/marginaleffects/) includes several vignettes and case studies. Main vignettes:

```{r, child = main}
```

Case studies:

```{r, child = internal}
```
