---
bibliography: library.bib
---

# What is this book about?

Our world is complex. To make sense of it, data analysts routinely fit sophisticated statistical or machine learning models. Interpreting the results produced by such models can be challenging, and researchers often struggle to communicate their findings to colleagues and stakeholders. *Model to Meaning* is a book designed to bridge that gap. It is a practical guide for anyone who needs to translate model outputs into accurate insights that are accessible to a wide audience.

*Model to Meaning* introduces a conceptual framework to help you describe the statistical quantities that can shed light on your research questions, use models to estimate those quantities, and communicate the results clearly and rigorously. Based on this conceptual framework, the book proposes an analysis workflow which can be applied in consistent fashion to (almost) any model you need to fit.

The key idea that underpins this workflow is that we can often transform the raw parameter estimates obtained by fitting a model into quantities that are much easier to interpret. Converting results to a scale that feels natural to our audience can improve transparency, communication, and impact.

Part I of the book lays the groundwork by encouraging analysts to clearly define their goals, and by introducing a simple conceptual framework to guide model interpretation. Part II describes how this framework can be operationalized through quantities of interest and tests, using concrete examples and real-world datasets. Part III presents detailed case studies which demonstrate how a consistent workflow can be applied in model-agnostic fashion to various settings.

This book was conceived to empower a broad range of people---including data scientists, researchers, and students---who want to improve their ability to interpret and communicate the results produced by statistical or machine learning models. The level of technical sophistication required to follow the presentation is modest. Readers familiar with empirical strategies like logistic regression should feel comfortable with most of the material. Some of the case studies in Part III cover more advanced modelling approaches, and extra reading materials are cited when appropriate.

Throughout, explanations are accompanied by detailed code examples in `R`, with `Python` translations collected in @sec-python. The main software library used to interpret models---`marginaleffects`---is free, open source, and well documented [@marginaleffects]. Readers who are not yet familiar with basic data manipulation commands in `R` or `Python` may want to refer to consult an additional reference, such as *Telling Stories with Data* [@Ale2023], *R for Data Science* [@Wic2023], or *Python for Data Analysis* [@Mck2022].
