source("helpers.R")
using("marginaleffects")

requiet("MASS")
requiet("quantreg")
requiet("survival")
requiet("pscl")
requiet("truncreg")
requiet("betareg")
requiet("lme4")
requiet("numDeriv")

# Cross-software fixtures for estimators covered by neither test-stata-misc.R
# nor the legacy stata.rds fixtures consumed by the test-pkg-* files.
# Generated by stata/models_fixtures.ado.
golden_path <- "stata/results/models.csv"
if (!file.exists(golden_path)) exit_file(golden_path)
golden <- read.csv(golden_path, stringsAsFactors = FALSE)
tested <- character()

# all.equal() silently falls back to an *absolute* comparison when the mean
# magnitude of the target drops below `tolerance`, which would let a nominally
# loose bound accept an unbounded relative error on small standard errors.
# Passing `scale` keeps every comparison relative.
expect_rel <- function(current, target, tolerance, info) {
    scale <- max(mean(abs(target)), .Machine$double.eps)
    expect_equal(current, target, tolerance = tolerance, scale = scale, info = info)
}

check_stata <- function(fixture, x, estimate, se = NA_real_, stata_order = NULL) {
    s <- golden[golden$fixture == fixture, , drop = FALSE]
    tested <<- union(tested, fixture)
    x <- as.data.frame(x)
    if (!is.null(stata_order)) x <- x[stata_order, , drop = FALSE]
    expect_equal(nrow(x), nrow(s), info = paste(fixture, "nrow"))
    if (nrow(x) != nrow(s)) return(invisible(NULL))
    expect_rel(x$estimate, s$estimate, estimate, paste(fixture, "estimate"))
    if (!is.na(se)) {
        expect_rel(x$std.error, s$std_error, se, paste(fixture, "std.error"))
    }
    invisible(NULL)
}

# The same six-command matrix misc.ado uses, so results line up with the
# response-scale fixtures for probit, cloglog and friends.
check_six <- function(prefix, model, estimate, se = NA_real_, ...) {
    check_stata(paste0(prefix, "_avg_predictions"), avg_predictions(model, ...), estimate, se)
    check_stata(paste0(prefix, "_avg_predictions_by"), avg_predictions(model, by = "cyl", ...), estimate, se)
    check_stata(paste0(prefix, "_avg_comparisons_factor"), avg_comparisons(model, variables = "am", ...), estimate, se)
    check_stata(paste0(prefix, "_avg_comparisons_factor_by"), avg_comparisons(model, variables = "am", by = "cyl", ...), estimate, se)
    check_stata(paste0(prefix, "_avg_slopes"), avg_slopes(model, variables = "hp", ...), estimate, se)
    check_stata(paste0(prefix, "_avg_slopes_by"), avg_slopes(model, variables = "hp", by = "cyl", ...), estimate, se)
}

check_three <- function(prefix, model, factor_var, numeric_var, estimate, se = NA_real_, se_slopes = se, ...) {
    check_stata(paste0(prefix, "_predictions"), avg_predictions(model, ...), estimate, se)
    check_stata(paste0(prefix, "_comparisons"), avg_comparisons(model, variables = factor_var, ...), estimate, se)
    check_stata(paste0(prefix, "_slopes"), avg_slopes(model, variables = numeric_var, ...), estimate, se_slopes)
}

# `pop` mirrors the deterministic exposure variable built in models_fixtures.ado.
dat <- transform(
    mtcars,
    am = factor(am),
    cyl = factor(cyl),
    pop = 100 + seq_len(nrow(mtcars)),
    lo = mpg - 1,
    hi = mpg + 1
)


# ---------------------------------------------------------------------------
# 1. Plain logit, and the family x link cross-product
# ---------------------------------------------------------------------------
# misc.ado covers probit and cloglog on this specification but never logit.
check_six("logit", glm(vs ~ hp + wt + am, family = binomial, data = dat), 1e-6, 1e-5)

# Non-canonical links: the inverse-link derivative that enters the delta method
# is no longer the variance function. The generator fits these with Stata's
# `irls`, which puts Stata on the expected information that glm() reports, so
# the comparison runs against the default vcov rather than a hand-built matrix.
# Starting values are supplied where the defaults put the linear predictor
# outside the link's domain.
check_six(
    "gaussian_log",
    glm(mpg ~ hp + wt + am, family = gaussian("log"), data = dat, start = c(3, 0, 0, 0)),
    1e-5, 1e-5
)
check_six(
    "poisson_identity",
    glm(carb ~ hp + wt + am, family = poisson("identity"), data = dat, start = c(1, 0, 0, 0)),
    1e-4, 1e-5
)
check_six(
    "inverse_gaussian_log",
    glm(mpg ~ hp + wt + am, family = inverse.gaussian("log"), data = dat, start = c(3, 0, 0, 0)),
    1e-4, 1e-5
)
# Gamma with the inverse link is canonical, so Stata needs no irls here.
check_six("gamma_inverse", glm(mpg ~ hp + wt + am, family = Gamma("inverse"), data = dat), 1e-3, 1e-3)


# ---------------------------------------------------------------------------
# 2. Offsets
# ---------------------------------------------------------------------------
# Stata's exposure(pop) is offset(log(pop)). The offset has to survive into the
# counterfactual predictions that comparisons and slopes are built from, not
# just into the fitted values.
mod_offset <- glm(carb ~ hp + wt + am + offset(log(pop)), family = poisson, data = dat)
check_six("poisson_exposure", mod_offset, 1e-6, 1e-4)
check_six("glm_poisson_exposure", mod_offset, 1e-6, 1e-4)


# ---------------------------------------------------------------------------
# 3. Quantile regression away from the median
# ---------------------------------------------------------------------------
# Standard errors are deliberately not compared: Stata's qreg and quantreg::rq
# use different variance estimators, which is already why the median fixtures
# in test-stata-misc.R carry a tolerance of 0.5. The point estimates are the
# meaningful cross-check.
check_six("quantile_25", suppressWarnings(quantreg::rq(mpg ~ hp + wt + am, tau = 0.25, data = dat)), 1e-4)
check_six("quantile_75", suppressWarnings(quantreg::rq(mpg ~ hp + wt + am, tau = 0.75, data = dat)), 1e-4)


# ---------------------------------------------------------------------------
# 4. Generalised linear mixed models
# ---------------------------------------------------------------------------
# re.form = NA matches Stata's predict(mu fixedonly); glmer's default nAGQ = 1
# matches intmethod(laplace). Tolerances absorb the remaining difference
# between the two Laplace implementations.
contraception <- read.csv("stata/databases/Contraception.csv")
contraception$usec <- as.integer(contraception$use == "Y")
contraception$urbanc <- factor(as.integer(contraception$urban == "Y"))
mod_glmm_logit <- lme4::glmer(
    usec ~ age + urbanc + (1 | district),
    family = binomial,
    data = contraception
)
check_three("mixed_logit", mod_glmm_logit, "urbanc", "age", 1e-3, 1e-2, re.form = NA)

mod_glmm_pois <- lme4::glmer(
    y ~ lbase + trt + lage + (1 | subject),
    family = poisson,
    data = MASS::epil
)
check_three("mixed_poisson", mod_glmm_pois, "trt", "lbase", 1e-3, 1e-2, re.form = NA)


# ---------------------------------------------------------------------------
# 5. Nonlinear least squares
# ---------------------------------------------------------------------------
# A mean function that is not linear in the parameters, so the Jacobian cannot
# be read off a model matrix.
mod_nls <- nls(mpg ~ b0 * exp(b1 * wt), data = mtcars, start = c(b0 = 50, b1 = -0.2))
check_stata("nls_slopes", avg_slopes(mod_nls, variables = "wt"), 1e-5, 1e-4)
check_stata("nls_predictions", avg_predictions(mod_nls), 1e-5, 1e-4)


# ---------------------------------------------------------------------------
# 6. Interval-censored regression
# ---------------------------------------------------------------------------
# Stata's intreg is survreg() with Surv(lo, hi, type = "interval2") and a
# Gaussian error. Standard errors are compared for slopes only: for the
# predictions and the factor contrast the two packages disagree about whether
# the ancillary scale parameter contributes to the delta method.
mod_intreg <- survival::survreg(
    survival::Surv(lo, hi, type = "interval2") ~ hp + wt + am,
    data = dat,
    dist = "gaussian"
)
check_three("intreg", mod_intreg, "am", "hp", 1e-5, se = NA_real_, se_slopes = 1e-4)


# ---------------------------------------------------------------------------
# 7. Zero-inflated Poisson and truncated regression
# ---------------------------------------------------------------------------
# The releveled copy gets a name of its own on purpose. data() loads into the
# global environment, and insight::get_data() re-resolves the model's `data`
# argument there rather than in this file's environment, so overwriting
# `bioChemists` locally would leave the counterfactual grids built from pscl's
# original level order -- silently flipping the sign of the `mar` contrast.
# `mar` is releveled because Stata's encode orders labels alphabetically, which
# puts Married first, while pscl ships Single first.
data("bioChemists", package = "pscl")
bio <- transform(
    bioChemists,
    fem = factor(fem, c("Men", "Women")),
    mar = factor(mar, c("Married", "Single"))
)
mod_zip <- pscl::zeroinfl(
    art ~ phd + ment + fem + mar + kid5 | ment + kid5 + fem,
    data = bio,
    dist = "poisson"
)
# marginaleffects sorts terms alphabetically; Stata keeps the dydx() order.
x <- avg_slopes(mod_zip, variables = c("phd", "ment", "fem", "mar", "kid5"))
check_stata("zip_response", x, 1e-3, 1e-3, stata_order = match(c("phd", "ment", "fem", "mar", "kid5"), x$term))
x <- avg_slopes(mod_zip, variables = c("ment", "fem", "kid5"), type = "zero")
check_stata("zip_zero_probability", x, 1e-3, 1e-3, stata_order = match(c("ment", "fem", "kid5"), x$term))
check_stata("zip_predictions", avg_predictions(mod_zip), 1e-5, 1e-4)

mod_truncreg <- truncreg::truncreg(
    art ~ phd + ment + fem,
    data = bio[bio$art > 0, , drop = FALSE],
    point = 0,
    direction = "left"
)
check_three("truncreg", mod_truncreg, "fem", "phd", 1e-3, 1e-3)


# ---------------------------------------------------------------------------
# 8. Parametric survival beyond Weibull
# ---------------------------------------------------------------------------
# streg's `time` option puts Stata in the accelerated-failure-time metric that
# survreg() uses, and predict(xb) is then type = "link".
#
# Standard errors are compared only for the exponential fit. Every other
# distribution carries a free scale parameter, and Stata's margins excludes the
# ancillary log(scale) from the delta method while survreg's vcov includes it.
# The exponential case has scale fixed at 1, and there the standard errors
# agree to six digits -- which is what identifies the scale parameter as the
# whole source of the discrepancy.
kidtran <- read.csv("stata/databases/kidtran.csv")
survival_se <- c(exponential = 1e-4, weibull = NA_real_, lognormal = NA_real_, loglogistic = NA_real_)
for (distribution in names(survival_se)) {
    mod <- survival::survreg(
        survival::Surv(time, delta) ~ age + factor(gender) + factor(race),
        data = kidtran,
        dist = distribution
    )
    se <- survival_se[[distribution]]
    check_stata(
        paste0("streg_", distribution, "_lp_slopes"),
        avg_slopes(mod, variables = c("age", "gender", "race"), type = "link"),
        1e-5, se
    )
    check_stata(
        paste0("streg_", distribution, "_lp_predictions"),
        avg_predictions(mod, type = "link"),
        1e-5, se
    )
}


# ---------------------------------------------------------------------------
# 9. Ordered probit
# ---------------------------------------------------------------------------
# misc.ado covers ologit on this specification; polr(method = "probit") is the
# counterpart of oprobit. Frequency weights are expanded exactly as the ado
# file does so the likelihood and covariance calculations coincide.
housing <- MASS::housing
housing$Sat <- ordered(housing$Sat, c("Low", "Medium", "High"))
housing$Infl <- factor(housing$Infl, c("Low", "Medium", "High"))
housing$Type <- factor(housing$Type, c("Tower", "Apartment", "Atrium", "Terrace"))
housing$Cont <- factor(housing$Cont, c("Low", "High"))
housing <- housing[rep(seq_len(nrow(housing)), housing$Freq), ]

mod_oprobit <- MASS::polr(Sat ~ Infl * Type + Cont, data = housing, Hess = TRUE, method = "probit")
p <- avg_predictions(mod_oprobit, type = "probs")
cmp <- avg_comparisons(mod_oprobit, variables = c("Infl", "Type", "Cont"), type = "probs")
stata_contrast_order <- c(
    "Infl|Medium - Low", "Infl|High - Low",
    "Type|Apartment - Tower", "Type|Atrium - Tower", "Type|Terrace - Tower",
    "Cont|High - Low"
)
for (j in seq_along(levels(housing$Sat))) {
    group <- levels(housing$Sat)[j]
    check_stata(paste0("oprobit_predictions_outcome", j), p[p$group == group, ], 1e-5, 1e-5)
    sub <- cmp[cmp$group == group, ]
    check_stata(
        paste0("oprobit_comparisons_outcome", j),
        sub,
        1e-4, 1e-5,
        stata_order = match(stata_contrast_order, paste(sub$term, sub$contrast, sep = "|"))
    )
}


# ---------------------------------------------------------------------------
# 10. Beta regression
# ---------------------------------------------------------------------------
# Stata's betareg reports the observed information (it sets e(vce) = "oim").
# betareg() reports the analytic *expected* information by default, and its own
# hessian = TRUE option substitutes optim's numerical Hessian, which on this fit
# is less accurate rather than more: it moves the slopes standard error from
# 0.4% away from Stata to 59% away. Differentiating the log-likelihood directly
# reproduces Stata to seven digits, which is what pins the bounds below.
betareg_observed_vcov <- function(model, y) {
    X <- stats::model.matrix(model, model = "mean")
    k <- ncol(X)
    estimates <- stats::coef(model)
    loglik <- function(par) {
        mu <- stats::plogis(as.vector(X %*% par[seq_len(k)]))
        phi <- par[k + 1L]
        sum(lgamma(phi) - lgamma(mu * phi) - lgamma((1 - mu) * phi) +
            (mu * phi - 1) * log(y) + ((1 - mu) * phi - 1) * log(1 - y))
    }
    V <- solve(-numDeriv::hessian(loglik, estimates))
    dimnames(V) <- dimnames(stats::vcov(model))
    V
}

data("GasolineYield", package = "betareg")
mod_betareg <- betareg::betareg(yield ~ batch + temp, data = GasolineYield)
V_betareg <- betareg_observed_vcov(mod_betareg, GasolineYield$yield)
check_stata("betareg_predictions", avg_predictions(mod_betareg, vcov = V_betareg), 1e-5, 1e-6)
# Stata orders the batch contrasts numerically; marginaleffects sorts the
# contrast labels as strings, which puts "10 - 1" first.
x <- avg_comparisons(mod_betareg, variables = "batch", vcov = V_betareg)
check_stata("betareg_comparisons", x, 1e-5, 1e-6, stata_order = match(paste(2:10, "- 1"), x$contrast))
check_stata("betareg_slopes", avg_slopes(mod_betareg, variables = "temp", vcov = V_betareg), 1e-5, 1e-4)


expect_equal(
    sort(unique(golden$fixture)),
    sort(tested),
    info = "every models.csv fixture is tested"
)
