source("helpers.R")
using("marginaleffects")

requiet("MASS")
requiet("sandwich")

# Cross-software fixtures for marginaleffects' *argument* surface. The
# companion file test-stata-misc.R covers a broad model x command matrix at a
# single setting of everything else; this one holds the complementary axis.
# Fixtures are generated by stata/args_fixtures.ado.
golden_path <- "stata/results/args.csv"
if (!file.exists(golden_path)) exit_file(golden_path)
golden <- read.csv(golden_path, stringsAsFactors = FALSE)
tested <- character()

# Each column is opt-in: pass a tolerance to compare it, leave it NA to skip.
# Stata exports estimate, std_error, statistic, p_value, conf_low and conf_high
# for every fixture, but not all of them are comparable for every quantity --
# `transform` drops the standard error, and orthogonal polynomial contrasts
# agree only up to a scale factor.
# all.equal() silently falls back to an *absolute* comparison when the mean
# magnitude of the target drops below `tolerance`, which would let a nominally
# loose bound accept an unbounded relative error on small standard errors.
# Passing `scale` keeps every comparison relative.
expect_rel <- function(current, target, tolerance, info) {
    scale <- max(mean(abs(target)), .Machine$double.eps)
    expect_equal(current, target, tolerance = tolerance, scale = scale, info = info)
}

check_stata <- function(
    fixture,
    x,
    estimate = NA_real_,
    se = NA_real_,
    ci = NA_real_,
    statistic = NA_real_,
    stata_order = NULL
) {
    s <- golden[golden$fixture == fixture, , drop = FALSE]
    if (!is.null(stata_order)) s <- s[stata_order, , drop = FALSE]
    tested <<- union(tested, fixture)
    expect_equal(nrow(x), nrow(s), info = paste(fixture, "nrow"))
    if (nrow(x) != nrow(s)) return(invisible(NULL))
    if (!is.na(estimate)) {
        expect_rel(x$estimate, s$estimate, estimate, paste(fixture, "estimate"))
    }
    if (!is.na(se)) {
        expect_rel(x$std.error, s$std_error, se, paste(fixture, "std.error"))
    }
    if (!is.na(ci)) {
        expect_rel(x$conf.low, s$conf_low, ci, paste(fixture, "conf.low"))
        expect_rel(x$conf.high, s$conf_high, ci, paste(fixture, "conf.high"))
    }
    if (!is.na(statistic)) {
        expect_rel(x$statistic, s$statistic, statistic, paste(fixture, "statistic"))
    }
    invisible(NULL)
}

# Stata reports a joint Wald chi-square after likelihood-based commands and an
# F after `regress`; marginaleffects always reports F. The two are related by
# chi2 = F * numerator-df, which is what the joint_chi2 branch compares.
check_joint <- function(fixture, x, tolerance) {
    s <- golden[golden$fixture == fixture, , drop = FALSE]
    tested <<- union(tested, fixture)
    expect_equal(nrow(s), 1L, info = paste(fixture, "nrow"))
    if (nrow(s) != 1L) return(invisible(NULL))
    x <- as.data.frame(x)
    expect_equal(x$df1, s$df, tolerance = 1e-8, info = paste(fixture, "df"))
    got <- if (identical(s$contrast, "joint_chi2")) x$statistic * x$df1 else x$statistic
    expect_rel(got, s$statistic, tolerance, paste(fixture, "statistic"))
    invisible(NULL)
}

# `clust` and `w` mirror the deterministic variables built in args_fixtures.ado.
dat <- transform(
    mtcars,
    cyl = factor(cyl),
    clust = (seq_len(nrow(mtcars)) - 1L) %% 8L + 1L,
    w = mpg,
    fw = ceiling(wt)
)

mod_lm <- lm(mpg ~ hp + wt + cyl, data = dat)
mod_logit <- glm(am ~ hp + wt + cyl, family = binomial, data = dat)
mod_poisson <- glm(carb ~ hp + wt + cyl, family = poisson, data = dat)


# ---------------------------------------------------------------------------
# 1. hypothesis = : Stata contrast operators
# ---------------------------------------------------------------------------
# Stata's contrast operators map onto marginaleffects' hypothesis formulas:
#   r.  -> ~reference      ar. -> ~sequential      g. -> ~meandev
#   pwcompare -> ~pairwise
# Two Stata operators have no equivalent here and are listed in `excluded`:
# h. (Helmert) uses a different contrast definition, and a. (~revsequential)
# is rejected by the formula interface even though the string appears in the
# list of recognised shortcuts.
hypothesis_map <- c(
    reference = "reference",
    sequential = "sequential",
    meandev = "meandev",
    pairwise = "pairwise"
)

models_hyp <- list(logit = mod_logit, lm = mod_lm, poisson = mod_poisson)
tol_hyp <- list(
    logit = c(estimate = 1e-6, se = 1e-4),
    lm = c(estimate = 1e-6, se = 1e-6),
    poisson = c(estimate = 1e-6, se = 1e-5)
)

for (nm in names(models_hyp)) {
    mod <- models_hyp[[nm]]
    tol <- tol_hyp[[nm]]
    check_stata(
        paste0(nm, "_margins_cyl"),
        avg_predictions(mod, variables = "cyl"),
        estimate = tol[["estimate"]],
        se = tol[["se"]]
    )
    for (key in names(hypothesis_map)) {
        h <- as.formula(paste0("~", hypothesis_map[[key]]))
        x <- avg_predictions(mod, variables = "cyl", hypothesis = h)
        check_stata(
            paste0(nm, "_hyp_", key),
            x,
            estimate = tol[["estimate"]],
            se = tol[["se"]]
        )
        # `pwcompare` prints no joint row, so no fixture is generated for it.
        # ~meandev produces one contrast per level, and those sum to zero: the
        # joint covariance is singular and marginaleffects inverts it directly.
        if (!key %in% c("pairwise", "meandev")) {
            check_joint(paste0(nm, "_hyp_", key, "_joint"), hypotheses(x, joint = TRUE), 5e-4)
        }
    }
    # Orthogonal polynomial contrasts agree only up to Stata's normalisation of
    # the contrast vectors (a factor of sqrt(3) for a three-level factor).
    # Estimate and standard error are rescaled by the same constant, so the
    # test statistic is invariant and is what gets compared.
    x <- avg_predictions(mod, variables = "cyl", hypothesis = ~poly)
    check_stata(paste0(nm, "_hyp_poly"), x, statistic = 5e-4)
    check_joint(paste0(nm, "_hyp_poly_joint"), hypotheses(x, joint = TRUE), 5e-4)
}

# A contrast computed separately inside each by-group. The counterfactual grid
# is built by hand because datagrid() drops columns that are not in the model,
# and `vs` is needed for the grouping.
cyl_levels <- levels(dat$cyl)
counterfactual_cyl <- do.call(
    rbind,
    lapply(cyl_levels, function(k) transform(dat, cyl = factor(k, levels = cyl_levels)))
)
check_stata(
    "logit_hyp_reference_by",
    predictions(mod_logit, newdata = counterfactual_cyl, by = c("cyl", "vs"), hypothesis = ~ reference | vs),
    estimate = 1e-6,
    se = 1e-4,
    # Stata orders contrast-major, marginaleffects group-major.
    stata_order = c(1, 3, 2, 4)
)
check_joint(
    "logit_hyp_reference_by_joint",
    hypotheses(
        predictions(mod_logit, newdata = counterfactual_cyl, by = c("cyl", "vs"), hypothesis = ~ reference | vs),
        joint = TRUE
    ),
    1e-3
)

# String and matrix hypotheses, against `lincom` and `test`.
check_stata(
    "logit_hyp_lincom",
    avg_predictions(mod_logit, variables = "cyl", hypothesis = "b2 - b1 = 0"),
    estimate = 1e-6,
    se = 1e-4
)
check_stata(
    "logit_hyp_slope_lincom",
    avg_slopes(mod_logit, variables = "hp", by = "cyl", hypothesis = "b2 - b1 = 0"),
    estimate = 1e-5,
    se = 1e-4
)
equality <- matrix(c(1, -1, 0, 1, 0, -1), ncol = 2)
check_joint(
    "logit_hyp_equality_joint",
    hypotheses(avg_predictions(mod_logit, variables = "cyl", hypothesis = equality), joint = TRUE),
    1e-4
)


# ---------------------------------------------------------------------------
# 2. vcov =
# ---------------------------------------------------------------------------
# Point estimates are invariant to the variance estimator, so these isolate
# the delta-method standard errors.
check_vcov <- function(prefix, model, vcov, estimate, se) {
    check_stata(paste0(prefix, "_predictions"), avg_predictions(model, vcov = vcov), estimate = estimate, se = se)
    check_stata(paste0(prefix, "_comparisons"), avg_comparisons(model, variables = "cyl", vcov = vcov), estimate = estimate, se = se)
    check_stata(paste0(prefix, "_slopes"), avg_slopes(model, variables = "hp", vcov = vcov), estimate = estimate, se = se)
}

# For `regress` the mapping is exact.
check_vcov("lm_vcov_hc1", mod_lm, "HC1", 1e-6, 1e-6)
check_vcov("lm_vcov_hc2", mod_lm, "HC2", 1e-6, 1e-6)
check_vcov("lm_vcov_hc3", mod_lm, "HC3", 1e-6, 1e-6)
check_vcov("lm_vcov_cluster", mod_lm, ~clust, 1e-6, 1e-6)

# After a maximum-likelihood command, Stata's vce(robust) is the plain HC0
# sandwich times n / (n - 1). No marginaleffects string abbreviates that, so
# the multiplier is applied explicitly. Without it the standard errors are off
# by about 1.6 percent, which is the whole point of pinning this down.
robust_stata <- function(model) {
    n <- stats::nobs(model)
    sandwich::vcovHC(model, type = "HC0") * n / (n - 1)
}
check_vcov("logit_vcov_robust", mod_logit, robust_stata(mod_logit), 1e-6, 1e-4)
check_vcov("poisson_vcov_robust", mod_poisson, robust_stata(mod_poisson), 1e-6, 1e-5)

# Clustered variance needs no such adjustment: marginaleffects already applies
# the same finite-sample corrections Stata does.
check_vcov("logit_vcov_cluster", mod_logit, ~clust, 1e-6, 1e-4)


# ---------------------------------------------------------------------------
# 3. type = "link"
# ---------------------------------------------------------------------------
# margins, predict(xb) skips the inverse-link chain rule, so this exercises a
# different Jacobian path from the response-scale fixtures in misc.ado. The
# model specifications match misc.ado's exactly.
dat_link <- transform(mtcars, am = factor(am), cyl = factor(cyl))
models_link <- list(
    logit_link = glm(vs ~ hp + wt + am, family = binomial, data = dat_link),
    probit_link = glm(vs ~ hp + wt + am, family = binomial("probit"), data = dat_link),
    poisson_link = glm(carb ~ hp + wt + am, family = poisson, data = dat_link),
    negative_binomial_link = suppressWarnings(MASS::glm.nb(carb ~ hp + wt + am, data = dat_link)),
    gamma_log_link = glm(mpg ~ hp + wt + am, family = Gamma("log"), data = dat_link)
)
# Same bounds as the response-scale fixtures for the same models: the looser
# ones absorb optimizer differences, not disagreement about the quantity.
tol_link <- list(
    logit_link = c(estimate = 1e-6, se = 1e-4),
    probit_link = c(estimate = 1e-5, se = 1e-4),
    poisson_link = c(estimate = 1e-6, se = 1e-5),
    negative_binomial_link = c(estimate = 1e-5, se = 1e-4),
    gamma_log_link = c(estimate = 1e-5, se = 1e-4)
)

for (nm in names(models_link)) {
    mod <- models_link[[nm]]
    tol <- tol_link[[nm]]
    e <- tol[["estimate"]]
    s <- tol[["se"]]
    check_stata(paste0(nm, "_avg_predictions"), avg_predictions(mod, type = "link"), estimate = e, se = s)
    check_stata(paste0(nm, "_avg_predictions_by"), avg_predictions(mod, by = "cyl", type = "link"), estimate = e, se = s)
    check_stata(paste0(nm, "_avg_comparisons_factor"), avg_comparisons(mod, variables = "am", type = "link"), estimate = e, se = s)
    check_stata(paste0(nm, "_avg_comparisons_factor_by"), avg_comparisons(mod, variables = "am", by = "cyl", type = "link"), estimate = e, se = s)
    check_stata(paste0(nm, "_avg_slopes"), avg_slopes(mod, variables = "hp", type = "link"), estimate = e, se = s)
    check_stata(paste0(nm, "_avg_slopes_by"), avg_slopes(mod, variables = "hp", by = "cyl", type = "link"), estimate = e, se = s)
}


# ---------------------------------------------------------------------------
# 4. newdata = datagrid(...)
# ---------------------------------------------------------------------------
# atmeans evaluates a single point rather than averaging, so it is used on
# well-conditioned fits only.
mod_lm_cont <- lm(mpg ~ hp + wt, data = mtcars)
mod_poisson_cont <- glm(carb ~ hp + wt, family = poisson, data = mtcars)

# The means are passed explicitly rather than left to datagrid()'s defaults:
# every value of mtcars$hp is a whole number, so datagrid() rounds its mean to
# 147 to preserve the apparent type, while Stata's atmeans uses 146.6875.
at_means <- function(model) {
    datagrid(model = model, hp = mean(mtcars$hp), wt = mean(mtcars$wt))
}

check_stata(
    "atmeans_lm_predictions",
    predictions(mod_lm_cont, newdata = at_means(mod_lm_cont)),
    estimate = 1e-6, se = 1e-6
)
check_stata(
    "atmeans_lm_slopes",
    slopes(mod_lm_cont, variables = c("hp", "wt"), newdata = at_means(mod_lm_cont)),
    estimate = 1e-6, se = 1e-6
)
# type = "response" is stated explicitly. The default for a glm is
# "invlink(link)", which builds the interval on the link scale and back
# transforms it, reporting no response-scale standard error at all; Stata's
# margins reports a delta-method standard error and a symmetric interval.
check_stata(
    "atmeans_poisson_predictions",
    predictions(mod_poisson_cont, newdata = at_means(mod_poisson_cont), type = "response"),
    estimate = 1e-6, se = 1e-5, ci = 1e-5
)
check_stata(
    "atmeans_poisson_slopes",
    slopes(mod_poisson_cont, variables = c("hp", "wt"), newdata = at_means(mod_poisson_cont)),
    estimate = 1e-6, se = 1e-5
)

# at() sets one or more variables to fixed values, leaves everything else at
# its observed value, and averages: a counterfactual grid followed by by=.
counterfactual <- function(data, ...) {
    values <- list(...)
    grid <- expand.grid(values, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)
    # expand.grid varies the first column fastest; Stata's _at index varies the
    # last one fastest, so the grid rows are reversed into Stata's order.
    grid <- grid[do.call(order, rev(grid)), , drop = FALSE]
    do.call(rbind, lapply(seq_len(nrow(grid)), function(i) {
        d <- data
        for (v in names(grid)) d[[v]] <- grid[[v]][i]
        d
    }))
}

mod_logit_cont <- glm(am ~ hp + wt, family = binomial, data = mtcars)
check_stata(
    "at_predictions_hp",
    predictions(mod_logit_cont, newdata = counterfactual(mtcars, hp = c(100, 150, 200)), by = "hp"),
    estimate = 1e-6, se = 1e-6, ci = 1e-6
)
check_stata(
    "at_slopes_wt",
    slopes(mod_logit_cont, variables = "hp", newdata = counterfactual(mtcars, wt = c(2, 3, 4)), by = "wt"),
    estimate = 1e-6, se = 1e-6, ci = 1e-6
)
check_stata(
    "at_predictions_grid",
    predictions(mod_logit_cont, newdata = counterfactual(mtcars, hp = c(100, 200), wt = c(2, 4)), by = c("hp", "wt")),
    estimate = 1e-6, se = 1e-6, ci = 1e-6
)
# at() over every level of a factor is the same quantity as variables=.
check_stata(
    "at_predictions_cyl",
    predictions(mod_logit, newdata = counterfactual_cyl, by = "cyl"),
    estimate = 1e-6, se = 1e-4
)


# ---------------------------------------------------------------------------
# 5. wts =
# ---------------------------------------------------------------------------
# Stata reuses the estimation weights when averaging the margins, so the same
# column is passed to both `weights` and `wts`.
mod_lm_w <- lm(mpg ~ hp + wt + cyl, data = dat, weights = w)
check_stata("wts_lm_aweight_predictions", avg_predictions(mod_lm_w, wts = "w"), estimate = 1e-6, se = 1e-6)
check_stata("wts_lm_aweight_comparisons", avg_comparisons(mod_lm_w, variables = "cyl", wts = "w"), estimate = 1e-6, se = 1e-6)
check_stata("wts_lm_aweight_slopes", avg_slopes(mod_lm_w, variables = "hp", wts = "w"), estimate = 1e-6, se = 1e-4)

mod_logit_fw <- suppressWarnings(glm(am ~ hp + wt + cyl, family = binomial, data = dat, weights = fw))
check_stata("wts_logit_fweight_predictions", avg_predictions(mod_logit_fw, wts = "fw"), estimate = 1e-6, se = 1e-5)
check_stata("wts_logit_fweight_comparisons", avg_comparisons(mod_logit_fw, variables = "cyl", wts = "fw"), estimate = 1e-6, se = 1e-5)
check_stata("wts_logit_fweight_slopes", avg_slopes(mod_logit_fw, variables = "hp", wts = "fw"), estimate = 1e-6, se = 1e-5)

# pweights imply vce(robust) in Stata, with the same n / (n - 1) multiplier.
mod_poisson_pw <- suppressWarnings(glm(carb ~ hp + wt + cyl, family = poisson, data = dat, weights = w))
V_pw <- robust_stata(mod_poisson_pw)
check_stata("wts_poisson_pweight_predictions", avg_predictions(mod_poisson_pw, wts = "w", vcov = V_pw), estimate = 1e-6, se = 1e-5)
check_stata("wts_poisson_pweight_comparisons", avg_comparisons(mod_poisson_pw, variables = "cyl", wts = "w", vcov = V_pw), estimate = 1e-6, se = 1e-5)
check_stata("wts_poisson_pweight_slopes", avg_slopes(mod_poisson_pw, variables = "hp", wts = "w", vcov = V_pw), estimate = 1e-6, se = 1e-5)


# ---------------------------------------------------------------------------
# 6. comparison = and slope =
# ---------------------------------------------------------------------------
# `margins, post` followed by nlcom is a ratio *of averages*, which is exactly
# what the "...avg" shortcuts compute. The non-averaged shortcuts average a
# per-row ratio instead and have no single-command Stata counterpart.
mod_vs <- glm(am ~ hp + wt + vs, family = binomial, data = transform(mtcars, vs = factor(vs)))
avg_family <- c("differenceavg", "ratioavg", "lnratioavg", "liftavg", "lnoravg")
nonlinear <- do.call(rbind, lapply(avg_family, function(k) {
    out <- avg_comparisons(mod_vs, variables = "vs", comparison = k)
    data.frame(estimate = out$estimate, std.error = out$std.error)
}))
check_stata("comparison_avg_family", nonlinear, estimate = 1e-6, se = 1e-5)

# transform= is applied after the delta method, and marginaleffects then drops
# the standard error, so only the point estimate is comparable.
check_stata(
    "comparison_transform_exp",
    avg_comparisons(mod_vs, variables = "vs", comparison = "lnoravg", transform = exp),
    estimate = 1e-6
)

# Elasticities, and their "...avg" variants. The two reach the same quantity by
# different Jacobian paths and must agree with Stata and with each other.
mod_elast <- glm(carb ~ hp + wt, family = poisson, data = mtcars)
for (slope in c("dydx", "eyex", "eydx", "dyex")) {
    fixture <- paste0("elast_", slope)
    check_stata(fixture, avg_slopes(mod_elast, variables = c("hp", "wt"), slope = slope), estimate = 1e-6, se = 1e-3)
    check_stata(fixture, avg_slopes(mod_elast, variables = c("hp", "wt"), slope = paste0(slope, "avg")), estimate = 1e-6, se = 1e-3)
}


# ---------------------------------------------------------------------------
# 7. by = with more than one variable
# ---------------------------------------------------------------------------
check_stata("by2_predictions", avg_predictions(mod_poisson, by = c("vs", "am")), estimate = 1e-6, se = 1e-5)
check_stata("by2_slopes", avg_slopes(mod_poisson, variables = "hp", by = c("vs", "am")), estimate = 1e-6, se = 1e-5)
check_stata(
    "by2_comparisons",
    avg_comparisons(mod_poisson, variables = "cyl", by = "vs"),
    estimate = 1e-6, se = 1e-5,
    stata_order = c(1, 3, 2, 4)
)


# ---------------------------------------------------------------------------
# 8. conf_level = and df =
# ---------------------------------------------------------------------------
# These are the only fixtures for which the exported conf_low/conf_high columns
# are load-bearing. `regress` margins use a t reference distribution with
# e(df_r) degrees of freedom, which marginaleffects reproduces only when df is
# supplied; the maximum-likelihood commands use z, which is the default.
lm_df <- df.residual(mod_lm)
check_stata("level90_lm_predictions", avg_predictions(mod_lm, conf_level = 0.90, df = lm_df), estimate = 1e-6, se = 1e-6, ci = 1e-6)
check_stata("level90_lm_slopes", avg_slopes(mod_lm, variables = "hp", conf_level = 0.90, df = lm_df), estimate = 1e-6, se = 1e-6, ci = 1e-6)
check_stata("level99_lm_slopes", avg_slopes(mod_lm, variables = "hp", conf_level = 0.99, df = lm_df), estimate = 1e-6, se = 1e-6, ci = 1e-6)
check_stata("level90_logit_predictions", avg_predictions(mod_logit, conf_level = 0.90), estimate = 1e-6, se = 1e-4, ci = 1e-4)
check_stata("level90_logit_slopes", avg_slopes(mod_logit, variables = "hp", conf_level = 0.90), estimate = 1e-6, se = 1e-4, ci = 1e-4)


# ---------------------------------------------------------------------------
# Every generated fixture must be asserted above or explicitly classified here.
# ---------------------------------------------------------------------------
excluded <- c(
    # Stata's h. operator contrasts each level against the mean of the levels
    # above it; marginaleffects' ~helmert uses a different definition, so the
    # two are not the same quantity.
    outer(c("logit", "lm", "poisson"), c("_hyp_helmert", "_hyp_helmert_joint"), paste0),
    # Stata's a. operator is the reverse of ar. The ~revsequential shortcut is
    # listed among the recognised hypothesis strings but the formula interface
    # rejects it, so there is nothing to compare against yet.
    outer(c("logit", "lm", "poisson"), c("_hyp_revsequential", "_hyp_revsequential_joint"), paste0),
    # The three grand-mean deviations sum to zero, so their joint covariance is
    # rank deficient. Stata reports the joint test at reduced rank (df = 2 for
    # three contrasts); hypotheses(joint = TRUE) inverts the matrix directly
    # and fails. The contrasts themselves are asserted above.
    outer(c("logit", "lm", "poisson"), "_hyp_meandev_joint", paste0),
    # With factors in the model, `atmeans` sets each indicator to its sample
    # mean, producing fractional dummies. datagrid()'s mean_or_mode picks the
    # modal level instead, so the two evaluate at different points.
    "atmeans_predictions_factor"
)
expect_equal(
    sort(unique(golden$fixture)),
    sort(union(tested, excluded)),
    info = "every args.csv fixture is tested or explicitly excluded"
)
