# Autocomment atime-based performance regression analysis on PRs
# Requires the file .ci/atime/tests.R
name: Benchmark

on:
  pull_request:
    branches:
      - '*'
    # types:
    #   - opened
    #   - reopened
    #   - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: Anirban166/Autocomment-atime-results@v1.3.1
