# Autocomment atime-based performance regression analysis on PRs
# Requires the file .ci/atime/tests.R
name: Benchmark

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'R/**'
      - 'src/**'
      - '.ci/atime/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  comment:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      repo_token: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Safe directory exception
        run: |
          git config --global --add safe.directory '*'
        shell: bash

      - name: R Setup
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install required dependencies for benchmark
        run: |
          install.packages(c("remotes", "bench", "dplyr", "tidyr", "ggplot2"))
          remotes::install_github("DavisVaughan/cross")
        shell: Rscript {0}

      - name: Run benchmark script
        run: |
          "Rscript .ci/atime/testsbis.R"
        shell : bash

      - name: Upload results
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: atime-results
          path: .ci/atime/

      - name: Push generated plot along with relevant information on the PR thread as a GH-bot comment
        run: |          
          # Comment contents:
          echo "[![Comparison Plot](./.ci/atime/benchmark_result.png)](./.ci/atime/benchmark_result.png)" >> report.md
          echo -e "\nGenerated via commit ${{ github.event.pull_request.head.sha }}" >> report.md
          echo -e "\nDownload link for the artifact containing the test results: [↓ atime-results.zip](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }})" >> report.md
          cml comment update report.md
        shell: bash
