name: r-check

on:
  push:
  pull_request:

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"
  _R_CHECK_TESTS_NLINES_: 0
  R_NOT_CRAN: "true"
  R_GH: "true"
  GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

jobs:
  check-r:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: vincentarelbundock/scrutin/.github/actions/install_r@main
        with:
          packages: any::rcmdcheck
          working-directory: r

      - uses: vincentarelbundock/scrutin/.github/actions/check_r@main
        with:
          working-directory: r

      - uses: vincentarelbundock/scrutin/.github/actions/install_scrutin@main

      - run: scrutin -r github -s filter.group=cheap
        working-directory: r
